/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BootRouteImport } from './routes/boot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SetupSchoolRouteImport } from './routes/setup.school'
import { Route as SetupAdminRouteImport } from './routes/setup.admin'
import { Route as ModulesModuleKeyRouteImport } from './routes/modules/$moduleKey'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminProcurementRouteImport } from './routes/admin/procurement'
import { Route as AdminMessagingRouteImport } from './routes/admin/messaging'
import { Route as AdminLicensingRouteImport } from './routes/admin/licensing'
import { Route as AdminLibraryRouteImport } from './routes/admin/library'
import { Route as AdminHrPayrollRouteImport } from './routes/admin/hr-payroll'
import { Route as AdminHostelRouteImport } from './routes/admin/hostel'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminClassesRouteImport } from './routes/admin/classes'
import { Route as AdminFleetIndexRouteImport } from './routes/admin/fleet/index'
import { Route as ModulesSisSettingsRouteImport } from './routes/modules/sis/settings'
import { Route as ModulesSisLearnersRouteImport } from './routes/modules/sis/learners'
import { Route as ModulesSisImportsRouteImport } from './routes/modules/sis/imports'
import { Route as ModulesSisGuardiansRouteImport } from './routes/modules/sis/guardians'
import { Route as ModulesSisGuardianRelationshipsRouteImport } from './routes/modules/sis/guardian-relationships'
import { Route as ModulesSisEnrolmentsRouteImport } from './routes/modules/sis/enrolments'
import { Route as ModulesSisApplicationsRouteImport } from './routes/modules/sis/applications'
import { Route as ModulesProcurementSuppliersRouteImport } from './routes/modules/procurement/suppliers'
import { Route as ModulesProcurementRequisitionsRouteImport } from './routes/modules/procurement/requisitions'
import { Route as ModulesProcurementPurchaseOrdersRouteImport } from './routes/modules/procurement/purchase-orders'
import { Route as ModulesProcurementGoodsReceiptsRouteImport } from './routes/modules/procurement/goods-receipts'
import { Route as ModulesHrPayrollPositionsRouteImport } from './routes/modules/hr-payroll/positions'
import { Route as ModulesHrPayrollImportsRouteImport } from './routes/modules/hr-payroll/imports'
import { Route as ModulesHrPayrollEmploymentRouteImport } from './routes/modules/hr-payroll/employment'
import { Route as ModulesHrPayrollEmployeesRouteImport } from './routes/modules/hr-payroll/employees'
import { Route as ModulesHrPayrollDepartmentsRouteImport } from './routes/modules/hr-payroll/departments'
import { Route as ModulesHrPayrollAvailabilityRouteImport } from './routes/modules/hr-payroll/availability'
import { Route as ModulesFleetVehiclesRouteImport } from './routes/modules/fleet/vehicles'
import { Route as ModulesFleetDriversRouteImport } from './routes/modules/fleet/drivers'
import { Route as ModulesFleetDailyLogRouteImport } from './routes/modules/fleet/daily-log'
import { Route as ModulesFinancePostingRequestsRouteImport } from './routes/modules/finance/posting-requests'
import { Route as ModulesFinanceJournalsRouteImport } from './routes/modules/finance/journals'
import { Route as ModulesFinanceCurrenciesRouteImport } from './routes/modules/finance/currencies'
import { Route as ModulesFinanceChartOfAccountsRouteImport } from './routes/modules/finance/chart-of-accounts'
import { Route as ModulesFinanceAccountingPeriodsRouteImport } from './routes/modules/finance/accounting-periods'
import { Route as ModulesFeesInvoicesRouteImport } from './routes/modules/fees/invoices'
import { Route as ModulesFeesImportsRouteImport } from './routes/modules/fees/imports'
import { Route as ModulesFeesFeeStructuresRouteImport } from './routes/modules/fees/fee-structures'
import { Route as ModulesFeesBillingAccountsRouteImport } from './routes/modules/fees/billing-accounts'
import { Route as ModulesAssetsInventoryStoresRouteImport } from './routes/modules/assets-inventory/stores'
import { Route as ModulesAssetsInventoryStockRouteImport } from './routes/modules/assets-inventory/stock'
import { Route as ModulesAssetsInventoryProcurementReceiptsRouteImport } from './routes/modules/assets-inventory/procurement-receipts'
import { Route as ModulesAssetsInventoryMovementsRouteImport } from './routes/modules/assets-inventory/movements'
import { Route as ModulesAssetsInventoryItemsRouteImport } from './routes/modules/assets-inventory/items'
import { Route as ModulesAcademicsTermsRouteImport } from './routes/modules/academics/terms'
import { Route as ModulesAcademicsTeachingAssignmentsRouteImport } from './routes/modules/academics/teaching-assignments'
import { Route as ModulesAcademicsTeachersRouteImport } from './routes/modules/academics/teachers'
import { Route as ModulesAcademicsSubjectsRouteImport } from './routes/modules/academics/subjects'
import { Route as ModulesAcademicsGradeLevelsRouteImport } from './routes/modules/academics/grade-levels'
import { Route as ModulesAcademicsClassesRouteImport } from './routes/modules/academics/classes'
import { Route as ModulesAcademicsAssessmentsRouteImport } from './routes/modules/academics/assessments'
import { Route as ModulesAcademicsAcademicYearsRouteImport } from './routes/modules/academics/academic-years'
import { Route as AdminFleetDriversRouteImport } from './routes/admin/fleet/drivers'
import { Route as AdminFleetDailyLogRouteImport } from './routes/admin/fleet/daily-log'
import { Route as AdminAgentRoutingRouteImport } from './routes/admin/agent/routing'
import { Route as AdminAgentProvidersRouteImport } from './routes/admin/agent/providers'
import { Route as ModulesSisLearnersLearnerIdRouteImport } from './routes/modules/sis/learners_.$learnerId'
import { Route as ModulesSisApplicationsApplicationIdRouteImport } from './routes/modules/sis/applications_.$applicationId'
import { Route as ModulesProcurementRequisitionsRequisitionIdRouteImport } from './routes/modules/procurement/requisitions_.$requisitionId'
import { Route as ModulesProcurementPurchaseOrdersPurchaseOrderIdRouteImport } from './routes/modules/procurement/purchase-orders_.$purchaseOrderId'
import { Route as ModulesAssetsInventoryMovementsMovementIdRouteImport } from './routes/modules/assets-inventory/movements_.$movementId'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SetupSchoolRoute = SetupSchoolRouteImport.update({
  id: '/setup/school',
  path: '/setup/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup/admin',
  path: '/setup/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleKeyRoute = ModulesModuleKeyRouteImport.update({
  id: '/$moduleKey',
  path: '/$moduleKey',
  getParentRoute: () => ModulesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcurementRoute = AdminProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagingRoute = AdminMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensingRoute = AdminLicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrPayrollRoute = AdminHrPayrollRouteImport.update({
  id: '/hr-payroll',
  path: '/hr-payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostelRoute = AdminHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetIndexRoute = AdminFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AdminRoute,
} as any)
const ModulesSisSettingsRoute = ModulesSisSettingsRouteImport.update({
  id: '/sis/settings',
  path: '/sis/settings',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSisLearnersRoute = ModulesSisLearnersRouteImport.update({
  id: '/sis/learners',
  path: '/sis/learners',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSisImportsRoute = ModulesSisImportsRouteImport.update({
  id: '/sis/imports',
  path: '/sis/imports',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSisGuardiansRoute = ModulesSisGuardiansRouteImport.update({
  id: '/sis/guardians',
  path: '/sis/guardians',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSisGuardianRelationshipsRoute =
  ModulesSisGuardianRelationshipsRouteImport.update({
    id: '/sis/guardian-relationships',
    path: '/sis/guardian-relationships',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesSisEnrolmentsRoute = ModulesSisEnrolmentsRouteImport.update({
  id: '/sis/enrolments',
  path: '/sis/enrolments',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSisApplicationsRoute = ModulesSisApplicationsRouteImport.update({
  id: '/sis/applications',
  path: '/sis/applications',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesProcurementSuppliersRoute =
  ModulesProcurementSuppliersRouteImport.update({
    id: '/procurement/suppliers',
    path: '/procurement/suppliers',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesProcurementRequisitionsRoute =
  ModulesProcurementRequisitionsRouteImport.update({
    id: '/procurement/requisitions',
    path: '/procurement/requisitions',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesProcurementPurchaseOrdersRoute =
  ModulesProcurementPurchaseOrdersRouteImport.update({
    id: '/procurement/purchase-orders',
    path: '/procurement/purchase-orders',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesProcurementGoodsReceiptsRoute =
  ModulesProcurementGoodsReceiptsRouteImport.update({
    id: '/procurement/goods-receipts',
    path: '/procurement/goods-receipts',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesHrPayrollPositionsRoute =
  ModulesHrPayrollPositionsRouteImport.update({
    id: '/hr-payroll/positions',
    path: '/hr-payroll/positions',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesHrPayrollImportsRoute = ModulesHrPayrollImportsRouteImport.update({
  id: '/hr-payroll/imports',
  path: '/hr-payroll/imports',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesHrPayrollEmploymentRoute =
  ModulesHrPayrollEmploymentRouteImport.update({
    id: '/hr-payroll/employment',
    path: '/hr-payroll/employment',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesHrPayrollEmployeesRoute =
  ModulesHrPayrollEmployeesRouteImport.update({
    id: '/hr-payroll/employees',
    path: '/hr-payroll/employees',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesHrPayrollDepartmentsRoute =
  ModulesHrPayrollDepartmentsRouteImport.update({
    id: '/hr-payroll/departments',
    path: '/hr-payroll/departments',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesHrPayrollAvailabilityRoute =
  ModulesHrPayrollAvailabilityRouteImport.update({
    id: '/hr-payroll/availability',
    path: '/hr-payroll/availability',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFleetVehiclesRoute = ModulesFleetVehiclesRouteImport.update({
  id: '/fleet/vehicles',
  path: '/fleet/vehicles',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFleetDriversRoute = ModulesFleetDriversRouteImport.update({
  id: '/fleet/drivers',
  path: '/fleet/drivers',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFleetDailyLogRoute = ModulesFleetDailyLogRouteImport.update({
  id: '/fleet/daily-log',
  path: '/fleet/daily-log',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFinancePostingRequestsRoute =
  ModulesFinancePostingRequestsRouteImport.update({
    id: '/finance/posting-requests',
    path: '/finance/posting-requests',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFinanceJournalsRoute = ModulesFinanceJournalsRouteImport.update({
  id: '/finance/journals',
  path: '/finance/journals',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFinanceCurrenciesRoute =
  ModulesFinanceCurrenciesRouteImport.update({
    id: '/finance/currencies',
    path: '/finance/currencies',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFinanceChartOfAccountsRoute =
  ModulesFinanceChartOfAccountsRouteImport.update({
    id: '/finance/chart-of-accounts',
    path: '/finance/chart-of-accounts',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFinanceAccountingPeriodsRoute =
  ModulesFinanceAccountingPeriodsRouteImport.update({
    id: '/finance/accounting-periods',
    path: '/finance/accounting-periods',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFeesInvoicesRoute = ModulesFeesInvoicesRouteImport.update({
  id: '/fees/invoices',
  path: '/fees/invoices',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFeesImportsRoute = ModulesFeesImportsRouteImport.update({
  id: '/fees/imports',
  path: '/fees/imports',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesFeesFeeStructuresRoute =
  ModulesFeesFeeStructuresRouteImport.update({
    id: '/fees/fee-structures',
    path: '/fees/fee-structures',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesFeesBillingAccountsRoute =
  ModulesFeesBillingAccountsRouteImport.update({
    id: '/fees/billing-accounts',
    path: '/fees/billing-accounts',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryStoresRoute =
  ModulesAssetsInventoryStoresRouteImport.update({
    id: '/assets-inventory/stores',
    path: '/assets-inventory/stores',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryStockRoute =
  ModulesAssetsInventoryStockRouteImport.update({
    id: '/assets-inventory/stock',
    path: '/assets-inventory/stock',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryProcurementReceiptsRoute =
  ModulesAssetsInventoryProcurementReceiptsRouteImport.update({
    id: '/assets-inventory/procurement-receipts',
    path: '/assets-inventory/procurement-receipts',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryMovementsRoute =
  ModulesAssetsInventoryMovementsRouteImport.update({
    id: '/assets-inventory/movements',
    path: '/assets-inventory/movements',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryItemsRoute =
  ModulesAssetsInventoryItemsRouteImport.update({
    id: '/assets-inventory/items',
    path: '/assets-inventory/items',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsTermsRoute = ModulesAcademicsTermsRouteImport.update({
  id: '/academics/terms',
  path: '/academics/terms',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesAcademicsTeachingAssignmentsRoute =
  ModulesAcademicsTeachingAssignmentsRouteImport.update({
    id: '/academics/teaching-assignments',
    path: '/academics/teaching-assignments',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsTeachersRoute =
  ModulesAcademicsTeachersRouteImport.update({
    id: '/academics/teachers',
    path: '/academics/teachers',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsSubjectsRoute =
  ModulesAcademicsSubjectsRouteImport.update({
    id: '/academics/subjects',
    path: '/academics/subjects',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsGradeLevelsRoute =
  ModulesAcademicsGradeLevelsRouteImport.update({
    id: '/academics/grade-levels',
    path: '/academics/grade-levels',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsClassesRoute = ModulesAcademicsClassesRouteImport.update({
  id: '/academics/classes',
  path: '/academics/classes',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesAcademicsAssessmentsRoute =
  ModulesAcademicsAssessmentsRouteImport.update({
    id: '/academics/assessments',
    path: '/academics/assessments',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAcademicsAcademicYearsRoute =
  ModulesAcademicsAcademicYearsRouteImport.update({
    id: '/academics/academic-years',
    path: '/academics/academic-years',
    getParentRoute: () => ModulesRoute,
  } as any)
const AdminFleetDriversRoute = AdminFleetDriversRouteImport.update({
  id: '/fleet/drivers',
  path: '/fleet/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetDailyLogRoute = AdminFleetDailyLogRouteImport.update({
  id: '/fleet/daily-log',
  path: '/fleet/daily-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoutingRoute = AdminAgentRoutingRouteImport.update({
  id: '/agent/routing',
  path: '/agent/routing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentProvidersRoute = AdminAgentProvidersRouteImport.update({
  id: '/agent/providers',
  path: '/agent/providers',
  getParentRoute: () => AdminRoute,
} as any)
const ModulesSisLearnersLearnerIdRoute =
  ModulesSisLearnersLearnerIdRouteImport.update({
    id: '/sis/learners_/$learnerId',
    path: '/sis/learners/$learnerId',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesSisApplicationsApplicationIdRoute =
  ModulesSisApplicationsApplicationIdRouteImport.update({
    id: '/sis/applications_/$applicationId',
    path: '/sis/applications/$applicationId',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesProcurementRequisitionsRequisitionIdRoute =
  ModulesProcurementRequisitionsRequisitionIdRouteImport.update({
    id: '/procurement/requisitions_/$requisitionId',
    path: '/procurement/requisitions/$requisitionId',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute =
  ModulesProcurementPurchaseOrdersPurchaseOrderIdRouteImport.update({
    id: '/procurement/purchase-orders_/$purchaseOrderId',
    path: '/procurement/purchase-orders/$purchaseOrderId',
    getParentRoute: () => ModulesRoute,
  } as any)
const ModulesAssetsInventoryMovementsMovementIdRoute =
  ModulesAssetsInventoryMovementsMovementIdRouteImport.update({
    id: '/assets-inventory/movements_/$movementId',
    path: '/assets-inventory/movements/$movementId',
    getParentRoute: () => ModulesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRouteWithChildren
  '/style-guide': typeof StyleGuideRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr-payroll': typeof AdminHrPayrollRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/licensing': typeof AdminLicensingRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agent/providers': typeof AdminAgentProvidersRoute
  '/admin/agent/routing': typeof AdminAgentRoutingRoute
  '/admin/fleet/daily-log': typeof AdminFleetDailyLogRoute
  '/admin/fleet/drivers': typeof AdminFleetDriversRoute
  '/modules/academics/academic-years': typeof ModulesAcademicsAcademicYearsRoute
  '/modules/academics/assessments': typeof ModulesAcademicsAssessmentsRoute
  '/modules/academics/classes': typeof ModulesAcademicsClassesRoute
  '/modules/academics/grade-levels': typeof ModulesAcademicsGradeLevelsRoute
  '/modules/academics/subjects': typeof ModulesAcademicsSubjectsRoute
  '/modules/academics/teachers': typeof ModulesAcademicsTeachersRoute
  '/modules/academics/teaching-assignments': typeof ModulesAcademicsTeachingAssignmentsRoute
  '/modules/academics/terms': typeof ModulesAcademicsTermsRoute
  '/modules/assets-inventory/items': typeof ModulesAssetsInventoryItemsRoute
  '/modules/assets-inventory/movements': typeof ModulesAssetsInventoryMovementsRoute
  '/modules/assets-inventory/procurement-receipts': typeof ModulesAssetsInventoryProcurementReceiptsRoute
  '/modules/assets-inventory/stock': typeof ModulesAssetsInventoryStockRoute
  '/modules/assets-inventory/stores': typeof ModulesAssetsInventoryStoresRoute
  '/modules/fees/billing-accounts': typeof ModulesFeesBillingAccountsRoute
  '/modules/fees/fee-structures': typeof ModulesFeesFeeStructuresRoute
  '/modules/fees/imports': typeof ModulesFeesImportsRoute
  '/modules/fees/invoices': typeof ModulesFeesInvoicesRoute
  '/modules/finance/accounting-periods': typeof ModulesFinanceAccountingPeriodsRoute
  '/modules/finance/chart-of-accounts': typeof ModulesFinanceChartOfAccountsRoute
  '/modules/finance/currencies': typeof ModulesFinanceCurrenciesRoute
  '/modules/finance/journals': typeof ModulesFinanceJournalsRoute
  '/modules/finance/posting-requests': typeof ModulesFinancePostingRequestsRoute
  '/modules/fleet/daily-log': typeof ModulesFleetDailyLogRoute
  '/modules/fleet/drivers': typeof ModulesFleetDriversRoute
  '/modules/fleet/vehicles': typeof ModulesFleetVehiclesRoute
  '/modules/hr-payroll/availability': typeof ModulesHrPayrollAvailabilityRoute
  '/modules/hr-payroll/departments': typeof ModulesHrPayrollDepartmentsRoute
  '/modules/hr-payroll/employees': typeof ModulesHrPayrollEmployeesRoute
  '/modules/hr-payroll/employment': typeof ModulesHrPayrollEmploymentRoute
  '/modules/hr-payroll/imports': typeof ModulesHrPayrollImportsRoute
  '/modules/hr-payroll/positions': typeof ModulesHrPayrollPositionsRoute
  '/modules/procurement/goods-receipts': typeof ModulesProcurementGoodsReceiptsRoute
  '/modules/procurement/purchase-orders': typeof ModulesProcurementPurchaseOrdersRoute
  '/modules/procurement/requisitions': typeof ModulesProcurementRequisitionsRoute
  '/modules/procurement/suppliers': typeof ModulesProcurementSuppliersRoute
  '/modules/sis/applications': typeof ModulesSisApplicationsRoute
  '/modules/sis/enrolments': typeof ModulesSisEnrolmentsRoute
  '/modules/sis/guardian-relationships': typeof ModulesSisGuardianRelationshipsRoute
  '/modules/sis/guardians': typeof ModulesSisGuardiansRoute
  '/modules/sis/imports': typeof ModulesSisImportsRoute
  '/modules/sis/learners': typeof ModulesSisLearnersRoute
  '/modules/sis/settings': typeof ModulesSisSettingsRoute
  '/admin/fleet': typeof AdminFleetIndexRoute
  '/modules/assets-inventory/movements/$movementId': typeof ModulesAssetsInventoryMovementsMovementIdRoute
  '/modules/procurement/purchase-orders/$purchaseOrderId': typeof ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute
  '/modules/procurement/requisitions/$requisitionId': typeof ModulesProcurementRequisitionsRequisitionIdRoute
  '/modules/sis/applications/$applicationId': typeof ModulesSisApplicationsApplicationIdRoute
  '/modules/sis/learners/$learnerId': typeof ModulesSisLearnersLearnerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRouteWithChildren
  '/style-guide': typeof StyleGuideRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr-payroll': typeof AdminHrPayrollRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/licensing': typeof AdminLicensingRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin': typeof AdminIndexRoute
  '/admin/agent/providers': typeof AdminAgentProvidersRoute
  '/admin/agent/routing': typeof AdminAgentRoutingRoute
  '/admin/fleet/daily-log': typeof AdminFleetDailyLogRoute
  '/admin/fleet/drivers': typeof AdminFleetDriversRoute
  '/modules/academics/academic-years': typeof ModulesAcademicsAcademicYearsRoute
  '/modules/academics/assessments': typeof ModulesAcademicsAssessmentsRoute
  '/modules/academics/classes': typeof ModulesAcademicsClassesRoute
  '/modules/academics/grade-levels': typeof ModulesAcademicsGradeLevelsRoute
  '/modules/academics/subjects': typeof ModulesAcademicsSubjectsRoute
  '/modules/academics/teachers': typeof ModulesAcademicsTeachersRoute
  '/modules/academics/teaching-assignments': typeof ModulesAcademicsTeachingAssignmentsRoute
  '/modules/academics/terms': typeof ModulesAcademicsTermsRoute
  '/modules/assets-inventory/items': typeof ModulesAssetsInventoryItemsRoute
  '/modules/assets-inventory/movements': typeof ModulesAssetsInventoryMovementsRoute
  '/modules/assets-inventory/procurement-receipts': typeof ModulesAssetsInventoryProcurementReceiptsRoute
  '/modules/assets-inventory/stock': typeof ModulesAssetsInventoryStockRoute
  '/modules/assets-inventory/stores': typeof ModulesAssetsInventoryStoresRoute
  '/modules/fees/billing-accounts': typeof ModulesFeesBillingAccountsRoute
  '/modules/fees/fee-structures': typeof ModulesFeesFeeStructuresRoute
  '/modules/fees/imports': typeof ModulesFeesImportsRoute
  '/modules/fees/invoices': typeof ModulesFeesInvoicesRoute
  '/modules/finance/accounting-periods': typeof ModulesFinanceAccountingPeriodsRoute
  '/modules/finance/chart-of-accounts': typeof ModulesFinanceChartOfAccountsRoute
  '/modules/finance/currencies': typeof ModulesFinanceCurrenciesRoute
  '/modules/finance/journals': typeof ModulesFinanceJournalsRoute
  '/modules/finance/posting-requests': typeof ModulesFinancePostingRequestsRoute
  '/modules/fleet/daily-log': typeof ModulesFleetDailyLogRoute
  '/modules/fleet/drivers': typeof ModulesFleetDriversRoute
  '/modules/fleet/vehicles': typeof ModulesFleetVehiclesRoute
  '/modules/hr-payroll/availability': typeof ModulesHrPayrollAvailabilityRoute
  '/modules/hr-payroll/departments': typeof ModulesHrPayrollDepartmentsRoute
  '/modules/hr-payroll/employees': typeof ModulesHrPayrollEmployeesRoute
  '/modules/hr-payroll/employment': typeof ModulesHrPayrollEmploymentRoute
  '/modules/hr-payroll/imports': typeof ModulesHrPayrollImportsRoute
  '/modules/hr-payroll/positions': typeof ModulesHrPayrollPositionsRoute
  '/modules/procurement/goods-receipts': typeof ModulesProcurementGoodsReceiptsRoute
  '/modules/procurement/purchase-orders': typeof ModulesProcurementPurchaseOrdersRoute
  '/modules/procurement/requisitions': typeof ModulesProcurementRequisitionsRoute
  '/modules/procurement/suppliers': typeof ModulesProcurementSuppliersRoute
  '/modules/sis/applications': typeof ModulesSisApplicationsRoute
  '/modules/sis/enrolments': typeof ModulesSisEnrolmentsRoute
  '/modules/sis/guardian-relationships': typeof ModulesSisGuardianRelationshipsRoute
  '/modules/sis/guardians': typeof ModulesSisGuardiansRoute
  '/modules/sis/imports': typeof ModulesSisImportsRoute
  '/modules/sis/learners': typeof ModulesSisLearnersRoute
  '/modules/sis/settings': typeof ModulesSisSettingsRoute
  '/admin/fleet': typeof AdminFleetIndexRoute
  '/modules/assets-inventory/movements/$movementId': typeof ModulesAssetsInventoryMovementsMovementIdRoute
  '/modules/procurement/purchase-orders/$purchaseOrderId': typeof ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute
  '/modules/procurement/requisitions/$requisitionId': typeof ModulesProcurementRequisitionsRequisitionIdRoute
  '/modules/sis/applications/$applicationId': typeof ModulesSisApplicationsApplicationIdRoute
  '/modules/sis/learners/$learnerId': typeof ModulesSisLearnersLearnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRouteWithChildren
  '/style-guide': typeof StyleGuideRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr-payroll': typeof AdminHrPayrollRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/licensing': typeof AdminLicensingRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agent/providers': typeof AdminAgentProvidersRoute
  '/admin/agent/routing': typeof AdminAgentRoutingRoute
  '/admin/fleet/daily-log': typeof AdminFleetDailyLogRoute
  '/admin/fleet/drivers': typeof AdminFleetDriversRoute
  '/modules/academics/academic-years': typeof ModulesAcademicsAcademicYearsRoute
  '/modules/academics/assessments': typeof ModulesAcademicsAssessmentsRoute
  '/modules/academics/classes': typeof ModulesAcademicsClassesRoute
  '/modules/academics/grade-levels': typeof ModulesAcademicsGradeLevelsRoute
  '/modules/academics/subjects': typeof ModulesAcademicsSubjectsRoute
  '/modules/academics/teachers': typeof ModulesAcademicsTeachersRoute
  '/modules/academics/teaching-assignments': typeof ModulesAcademicsTeachingAssignmentsRoute
  '/modules/academics/terms': typeof ModulesAcademicsTermsRoute
  '/modules/assets-inventory/items': typeof ModulesAssetsInventoryItemsRoute
  '/modules/assets-inventory/movements': typeof ModulesAssetsInventoryMovementsRoute
  '/modules/assets-inventory/procurement-receipts': typeof ModulesAssetsInventoryProcurementReceiptsRoute
  '/modules/assets-inventory/stock': typeof ModulesAssetsInventoryStockRoute
  '/modules/assets-inventory/stores': typeof ModulesAssetsInventoryStoresRoute
  '/modules/fees/billing-accounts': typeof ModulesFeesBillingAccountsRoute
  '/modules/fees/fee-structures': typeof ModulesFeesFeeStructuresRoute
  '/modules/fees/imports': typeof ModulesFeesImportsRoute
  '/modules/fees/invoices': typeof ModulesFeesInvoicesRoute
  '/modules/finance/accounting-periods': typeof ModulesFinanceAccountingPeriodsRoute
  '/modules/finance/chart-of-accounts': typeof ModulesFinanceChartOfAccountsRoute
  '/modules/finance/currencies': typeof ModulesFinanceCurrenciesRoute
  '/modules/finance/journals': typeof ModulesFinanceJournalsRoute
  '/modules/finance/posting-requests': typeof ModulesFinancePostingRequestsRoute
  '/modules/fleet/daily-log': typeof ModulesFleetDailyLogRoute
  '/modules/fleet/drivers': typeof ModulesFleetDriversRoute
  '/modules/fleet/vehicles': typeof ModulesFleetVehiclesRoute
  '/modules/hr-payroll/availability': typeof ModulesHrPayrollAvailabilityRoute
  '/modules/hr-payroll/departments': typeof ModulesHrPayrollDepartmentsRoute
  '/modules/hr-payroll/employees': typeof ModulesHrPayrollEmployeesRoute
  '/modules/hr-payroll/employment': typeof ModulesHrPayrollEmploymentRoute
  '/modules/hr-payroll/imports': typeof ModulesHrPayrollImportsRoute
  '/modules/hr-payroll/positions': typeof ModulesHrPayrollPositionsRoute
  '/modules/procurement/goods-receipts': typeof ModulesProcurementGoodsReceiptsRoute
  '/modules/procurement/purchase-orders': typeof ModulesProcurementPurchaseOrdersRoute
  '/modules/procurement/requisitions': typeof ModulesProcurementRequisitionsRoute
  '/modules/procurement/suppliers': typeof ModulesProcurementSuppliersRoute
  '/modules/sis/applications': typeof ModulesSisApplicationsRoute
  '/modules/sis/enrolments': typeof ModulesSisEnrolmentsRoute
  '/modules/sis/guardian-relationships': typeof ModulesSisGuardianRelationshipsRoute
  '/modules/sis/guardians': typeof ModulesSisGuardiansRoute
  '/modules/sis/imports': typeof ModulesSisImportsRoute
  '/modules/sis/learners': typeof ModulesSisLearnersRoute
  '/modules/sis/settings': typeof ModulesSisSettingsRoute
  '/admin/fleet/': typeof AdminFleetIndexRoute
  '/modules/assets-inventory/movements_/$movementId': typeof ModulesAssetsInventoryMovementsMovementIdRoute
  '/modules/procurement/purchase-orders_/$purchaseOrderId': typeof ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute
  '/modules/procurement/requisitions_/$requisitionId': typeof ModulesProcurementRequisitionsRequisitionIdRoute
  '/modules/sis/applications_/$applicationId': typeof ModulesSisApplicationsApplicationIdRoute
  '/modules/sis/learners_/$learnerId': typeof ModulesSisLearnersLearnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boot'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/modules'
    | '/style-guide'
    | '/admin/classes'
    | '/admin/departments'
    | '/admin/fees'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr-payroll'
    | '/admin/library'
    | '/admin/licensing'
    | '/admin/messaging'
    | '/admin/procurement'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/users'
    | '/modules/$moduleKey'
    | '/setup/admin'
    | '/setup/school'
    | '/admin/'
    | '/admin/agent/providers'
    | '/admin/agent/routing'
    | '/admin/fleet/daily-log'
    | '/admin/fleet/drivers'
    | '/modules/academics/academic-years'
    | '/modules/academics/assessments'
    | '/modules/academics/classes'
    | '/modules/academics/grade-levels'
    | '/modules/academics/subjects'
    | '/modules/academics/teachers'
    | '/modules/academics/teaching-assignments'
    | '/modules/academics/terms'
    | '/modules/assets-inventory/items'
    | '/modules/assets-inventory/movements'
    | '/modules/assets-inventory/procurement-receipts'
    | '/modules/assets-inventory/stock'
    | '/modules/assets-inventory/stores'
    | '/modules/fees/billing-accounts'
    | '/modules/fees/fee-structures'
    | '/modules/fees/imports'
    | '/modules/fees/invoices'
    | '/modules/finance/accounting-periods'
    | '/modules/finance/chart-of-accounts'
    | '/modules/finance/currencies'
    | '/modules/finance/journals'
    | '/modules/finance/posting-requests'
    | '/modules/fleet/daily-log'
    | '/modules/fleet/drivers'
    | '/modules/fleet/vehicles'
    | '/modules/hr-payroll/availability'
    | '/modules/hr-payroll/departments'
    | '/modules/hr-payroll/employees'
    | '/modules/hr-payroll/employment'
    | '/modules/hr-payroll/imports'
    | '/modules/hr-payroll/positions'
    | '/modules/procurement/goods-receipts'
    | '/modules/procurement/purchase-orders'
    | '/modules/procurement/requisitions'
    | '/modules/procurement/suppliers'
    | '/modules/sis/applications'
    | '/modules/sis/enrolments'
    | '/modules/sis/guardian-relationships'
    | '/modules/sis/guardians'
    | '/modules/sis/imports'
    | '/modules/sis/learners'
    | '/modules/sis/settings'
    | '/admin/fleet'
    | '/modules/assets-inventory/movements/$movementId'
    | '/modules/procurement/purchase-orders/$purchaseOrderId'
    | '/modules/procurement/requisitions/$requisitionId'
    | '/modules/sis/applications/$applicationId'
    | '/modules/sis/learners/$learnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boot'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/modules'
    | '/style-guide'
    | '/admin/classes'
    | '/admin/departments'
    | '/admin/fees'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr-payroll'
    | '/admin/library'
    | '/admin/licensing'
    | '/admin/messaging'
    | '/admin/procurement'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/users'
    | '/modules/$moduleKey'
    | '/setup/admin'
    | '/setup/school'
    | '/admin'
    | '/admin/agent/providers'
    | '/admin/agent/routing'
    | '/admin/fleet/daily-log'
    | '/admin/fleet/drivers'
    | '/modules/academics/academic-years'
    | '/modules/academics/assessments'
    | '/modules/academics/classes'
    | '/modules/academics/grade-levels'
    | '/modules/academics/subjects'
    | '/modules/academics/teachers'
    | '/modules/academics/teaching-assignments'
    | '/modules/academics/terms'
    | '/modules/assets-inventory/items'
    | '/modules/assets-inventory/movements'
    | '/modules/assets-inventory/procurement-receipts'
    | '/modules/assets-inventory/stock'
    | '/modules/assets-inventory/stores'
    | '/modules/fees/billing-accounts'
    | '/modules/fees/fee-structures'
    | '/modules/fees/imports'
    | '/modules/fees/invoices'
    | '/modules/finance/accounting-periods'
    | '/modules/finance/chart-of-accounts'
    | '/modules/finance/currencies'
    | '/modules/finance/journals'
    | '/modules/finance/posting-requests'
    | '/modules/fleet/daily-log'
    | '/modules/fleet/drivers'
    | '/modules/fleet/vehicles'
    | '/modules/hr-payroll/availability'
    | '/modules/hr-payroll/departments'
    | '/modules/hr-payroll/employees'
    | '/modules/hr-payroll/employment'
    | '/modules/hr-payroll/imports'
    | '/modules/hr-payroll/positions'
    | '/modules/procurement/goods-receipts'
    | '/modules/procurement/purchase-orders'
    | '/modules/procurement/requisitions'
    | '/modules/procurement/suppliers'
    | '/modules/sis/applications'
    | '/modules/sis/enrolments'
    | '/modules/sis/guardian-relationships'
    | '/modules/sis/guardians'
    | '/modules/sis/imports'
    | '/modules/sis/learners'
    | '/modules/sis/settings'
    | '/admin/fleet'
    | '/modules/assets-inventory/movements/$movementId'
    | '/modules/procurement/purchase-orders/$purchaseOrderId'
    | '/modules/procurement/requisitions/$requisitionId'
    | '/modules/sis/applications/$applicationId'
    | '/modules/sis/learners/$learnerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boot'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/modules'
    | '/style-guide'
    | '/admin/classes'
    | '/admin/departments'
    | '/admin/fees'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr-payroll'
    | '/admin/library'
    | '/admin/licensing'
    | '/admin/messaging'
    | '/admin/procurement'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/users'
    | '/modules/$moduleKey'
    | '/setup/admin'
    | '/setup/school'
    | '/admin/'
    | '/admin/agent/providers'
    | '/admin/agent/routing'
    | '/admin/fleet/daily-log'
    | '/admin/fleet/drivers'
    | '/modules/academics/academic-years'
    | '/modules/academics/assessments'
    | '/modules/academics/classes'
    | '/modules/academics/grade-levels'
    | '/modules/academics/subjects'
    | '/modules/academics/teachers'
    | '/modules/academics/teaching-assignments'
    | '/modules/academics/terms'
    | '/modules/assets-inventory/items'
    | '/modules/assets-inventory/movements'
    | '/modules/assets-inventory/procurement-receipts'
    | '/modules/assets-inventory/stock'
    | '/modules/assets-inventory/stores'
    | '/modules/fees/billing-accounts'
    | '/modules/fees/fee-structures'
    | '/modules/fees/imports'
    | '/modules/fees/invoices'
    | '/modules/finance/accounting-periods'
    | '/modules/finance/chart-of-accounts'
    | '/modules/finance/currencies'
    | '/modules/finance/journals'
    | '/modules/finance/posting-requests'
    | '/modules/fleet/daily-log'
    | '/modules/fleet/drivers'
    | '/modules/fleet/vehicles'
    | '/modules/hr-payroll/availability'
    | '/modules/hr-payroll/departments'
    | '/modules/hr-payroll/employees'
    | '/modules/hr-payroll/employment'
    | '/modules/hr-payroll/imports'
    | '/modules/hr-payroll/positions'
    | '/modules/procurement/goods-receipts'
    | '/modules/procurement/purchase-orders'
    | '/modules/procurement/requisitions'
    | '/modules/procurement/suppliers'
    | '/modules/sis/applications'
    | '/modules/sis/enrolments'
    | '/modules/sis/guardian-relationships'
    | '/modules/sis/guardians'
    | '/modules/sis/imports'
    | '/modules/sis/learners'
    | '/modules/sis/settings'
    | '/admin/fleet/'
    | '/modules/assets-inventory/movements_/$movementId'
    | '/modules/procurement/purchase-orders_/$purchaseOrderId'
    | '/modules/procurement/requisitions_/$requisitionId'
    | '/modules/sis/applications_/$applicationId'
    | '/modules/sis/learners_/$learnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BootRoute: typeof BootRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  StyleGuideRoute: typeof StyleGuideRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SetupSchoolRoute: typeof SetupSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/setup/school': {
      id: '/setup/school'
      path: '/setup/school'
      fullPath: '/setup/school'
      preLoaderRoute: typeof SetupSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/admin': {
      id: '/setup/admin'
      path: '/setup/admin'
      fullPath: '/setup/admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleKey': {
      id: '/modules/$moduleKey'
      path: '/$moduleKey'
      fullPath: '/modules/$moduleKey'
      preLoaderRoute: typeof ModulesModuleKeyRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procurement': {
      id: '/admin/procurement'
      path: '/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AdminProcurementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messaging': {
      id: '/admin/messaging'
      path: '/messaging'
      fullPath: '/admin/messaging'
      preLoaderRoute: typeof AdminMessagingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licensing': {
      id: '/admin/licensing'
      path: '/licensing'
      fullPath: '/admin/licensing'
      preLoaderRoute: typeof AdminLicensingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr-payroll': {
      id: '/admin/hr-payroll'
      path: '/hr-payroll'
      fullPath: '/admin/hr-payroll'
      preLoaderRoute: typeof AdminHrPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostel': {
      id: '/admin/hostel'
      path: '/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AdminHostelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/': {
      id: '/admin/fleet/'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/modules/sis/settings': {
      id: '/modules/sis/settings'
      path: '/sis/settings'
      fullPath: '/modules/sis/settings'
      preLoaderRoute: typeof ModulesSisSettingsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/learners': {
      id: '/modules/sis/learners'
      path: '/sis/learners'
      fullPath: '/modules/sis/learners'
      preLoaderRoute: typeof ModulesSisLearnersRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/imports': {
      id: '/modules/sis/imports'
      path: '/sis/imports'
      fullPath: '/modules/sis/imports'
      preLoaderRoute: typeof ModulesSisImportsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/guardians': {
      id: '/modules/sis/guardians'
      path: '/sis/guardians'
      fullPath: '/modules/sis/guardians'
      preLoaderRoute: typeof ModulesSisGuardiansRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/guardian-relationships': {
      id: '/modules/sis/guardian-relationships'
      path: '/sis/guardian-relationships'
      fullPath: '/modules/sis/guardian-relationships'
      preLoaderRoute: typeof ModulesSisGuardianRelationshipsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/enrolments': {
      id: '/modules/sis/enrolments'
      path: '/sis/enrolments'
      fullPath: '/modules/sis/enrolments'
      preLoaderRoute: typeof ModulesSisEnrolmentsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/applications': {
      id: '/modules/sis/applications'
      path: '/sis/applications'
      fullPath: '/modules/sis/applications'
      preLoaderRoute: typeof ModulesSisApplicationsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/suppliers': {
      id: '/modules/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/modules/procurement/suppliers'
      preLoaderRoute: typeof ModulesProcurementSuppliersRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/requisitions': {
      id: '/modules/procurement/requisitions'
      path: '/procurement/requisitions'
      fullPath: '/modules/procurement/requisitions'
      preLoaderRoute: typeof ModulesProcurementRequisitionsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/purchase-orders': {
      id: '/modules/procurement/purchase-orders'
      path: '/procurement/purchase-orders'
      fullPath: '/modules/procurement/purchase-orders'
      preLoaderRoute: typeof ModulesProcurementPurchaseOrdersRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/goods-receipts': {
      id: '/modules/procurement/goods-receipts'
      path: '/procurement/goods-receipts'
      fullPath: '/modules/procurement/goods-receipts'
      preLoaderRoute: typeof ModulesProcurementGoodsReceiptsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/positions': {
      id: '/modules/hr-payroll/positions'
      path: '/hr-payroll/positions'
      fullPath: '/modules/hr-payroll/positions'
      preLoaderRoute: typeof ModulesHrPayrollPositionsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/imports': {
      id: '/modules/hr-payroll/imports'
      path: '/hr-payroll/imports'
      fullPath: '/modules/hr-payroll/imports'
      preLoaderRoute: typeof ModulesHrPayrollImportsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/employment': {
      id: '/modules/hr-payroll/employment'
      path: '/hr-payroll/employment'
      fullPath: '/modules/hr-payroll/employment'
      preLoaderRoute: typeof ModulesHrPayrollEmploymentRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/employees': {
      id: '/modules/hr-payroll/employees'
      path: '/hr-payroll/employees'
      fullPath: '/modules/hr-payroll/employees'
      preLoaderRoute: typeof ModulesHrPayrollEmployeesRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/departments': {
      id: '/modules/hr-payroll/departments'
      path: '/hr-payroll/departments'
      fullPath: '/modules/hr-payroll/departments'
      preLoaderRoute: typeof ModulesHrPayrollDepartmentsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/hr-payroll/availability': {
      id: '/modules/hr-payroll/availability'
      path: '/hr-payroll/availability'
      fullPath: '/modules/hr-payroll/availability'
      preLoaderRoute: typeof ModulesHrPayrollAvailabilityRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fleet/vehicles': {
      id: '/modules/fleet/vehicles'
      path: '/fleet/vehicles'
      fullPath: '/modules/fleet/vehicles'
      preLoaderRoute: typeof ModulesFleetVehiclesRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fleet/drivers': {
      id: '/modules/fleet/drivers'
      path: '/fleet/drivers'
      fullPath: '/modules/fleet/drivers'
      preLoaderRoute: typeof ModulesFleetDriversRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fleet/daily-log': {
      id: '/modules/fleet/daily-log'
      path: '/fleet/daily-log'
      fullPath: '/modules/fleet/daily-log'
      preLoaderRoute: typeof ModulesFleetDailyLogRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/finance/posting-requests': {
      id: '/modules/finance/posting-requests'
      path: '/finance/posting-requests'
      fullPath: '/modules/finance/posting-requests'
      preLoaderRoute: typeof ModulesFinancePostingRequestsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/finance/journals': {
      id: '/modules/finance/journals'
      path: '/finance/journals'
      fullPath: '/modules/finance/journals'
      preLoaderRoute: typeof ModulesFinanceJournalsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/finance/currencies': {
      id: '/modules/finance/currencies'
      path: '/finance/currencies'
      fullPath: '/modules/finance/currencies'
      preLoaderRoute: typeof ModulesFinanceCurrenciesRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/finance/chart-of-accounts': {
      id: '/modules/finance/chart-of-accounts'
      path: '/finance/chart-of-accounts'
      fullPath: '/modules/finance/chart-of-accounts'
      preLoaderRoute: typeof ModulesFinanceChartOfAccountsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/finance/accounting-periods': {
      id: '/modules/finance/accounting-periods'
      path: '/finance/accounting-periods'
      fullPath: '/modules/finance/accounting-periods'
      preLoaderRoute: typeof ModulesFinanceAccountingPeriodsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fees/invoices': {
      id: '/modules/fees/invoices'
      path: '/fees/invoices'
      fullPath: '/modules/fees/invoices'
      preLoaderRoute: typeof ModulesFeesInvoicesRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fees/imports': {
      id: '/modules/fees/imports'
      path: '/fees/imports'
      fullPath: '/modules/fees/imports'
      preLoaderRoute: typeof ModulesFeesImportsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fees/fee-structures': {
      id: '/modules/fees/fee-structures'
      path: '/fees/fee-structures'
      fullPath: '/modules/fees/fee-structures'
      preLoaderRoute: typeof ModulesFeesFeeStructuresRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/fees/billing-accounts': {
      id: '/modules/fees/billing-accounts'
      path: '/fees/billing-accounts'
      fullPath: '/modules/fees/billing-accounts'
      preLoaderRoute: typeof ModulesFeesBillingAccountsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/stores': {
      id: '/modules/assets-inventory/stores'
      path: '/assets-inventory/stores'
      fullPath: '/modules/assets-inventory/stores'
      preLoaderRoute: typeof ModulesAssetsInventoryStoresRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/stock': {
      id: '/modules/assets-inventory/stock'
      path: '/assets-inventory/stock'
      fullPath: '/modules/assets-inventory/stock'
      preLoaderRoute: typeof ModulesAssetsInventoryStockRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/procurement-receipts': {
      id: '/modules/assets-inventory/procurement-receipts'
      path: '/assets-inventory/procurement-receipts'
      fullPath: '/modules/assets-inventory/procurement-receipts'
      preLoaderRoute: typeof ModulesAssetsInventoryProcurementReceiptsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/movements': {
      id: '/modules/assets-inventory/movements'
      path: '/assets-inventory/movements'
      fullPath: '/modules/assets-inventory/movements'
      preLoaderRoute: typeof ModulesAssetsInventoryMovementsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/items': {
      id: '/modules/assets-inventory/items'
      path: '/assets-inventory/items'
      fullPath: '/modules/assets-inventory/items'
      preLoaderRoute: typeof ModulesAssetsInventoryItemsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/terms': {
      id: '/modules/academics/terms'
      path: '/academics/terms'
      fullPath: '/modules/academics/terms'
      preLoaderRoute: typeof ModulesAcademicsTermsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/teaching-assignments': {
      id: '/modules/academics/teaching-assignments'
      path: '/academics/teaching-assignments'
      fullPath: '/modules/academics/teaching-assignments'
      preLoaderRoute: typeof ModulesAcademicsTeachingAssignmentsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/teachers': {
      id: '/modules/academics/teachers'
      path: '/academics/teachers'
      fullPath: '/modules/academics/teachers'
      preLoaderRoute: typeof ModulesAcademicsTeachersRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/subjects': {
      id: '/modules/academics/subjects'
      path: '/academics/subjects'
      fullPath: '/modules/academics/subjects'
      preLoaderRoute: typeof ModulesAcademicsSubjectsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/grade-levels': {
      id: '/modules/academics/grade-levels'
      path: '/academics/grade-levels'
      fullPath: '/modules/academics/grade-levels'
      preLoaderRoute: typeof ModulesAcademicsGradeLevelsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/classes': {
      id: '/modules/academics/classes'
      path: '/academics/classes'
      fullPath: '/modules/academics/classes'
      preLoaderRoute: typeof ModulesAcademicsClassesRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/assessments': {
      id: '/modules/academics/assessments'
      path: '/academics/assessments'
      fullPath: '/modules/academics/assessments'
      preLoaderRoute: typeof ModulesAcademicsAssessmentsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/academics/academic-years': {
      id: '/modules/academics/academic-years'
      path: '/academics/academic-years'
      fullPath: '/modules/academics/academic-years'
      preLoaderRoute: typeof ModulesAcademicsAcademicYearsRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/admin/fleet/drivers': {
      id: '/admin/fleet/drivers'
      path: '/fleet/drivers'
      fullPath: '/admin/fleet/drivers'
      preLoaderRoute: typeof AdminFleetDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet/daily-log': {
      id: '/admin/fleet/daily-log'
      path: '/fleet/daily-log'
      fullPath: '/admin/fleet/daily-log'
      preLoaderRoute: typeof AdminFleetDailyLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent/routing': {
      id: '/admin/agent/routing'
      path: '/agent/routing'
      fullPath: '/admin/agent/routing'
      preLoaderRoute: typeof AdminAgentRoutingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent/providers': {
      id: '/admin/agent/providers'
      path: '/agent/providers'
      fullPath: '/admin/agent/providers'
      preLoaderRoute: typeof AdminAgentProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/modules/sis/learners_/$learnerId': {
      id: '/modules/sis/learners_/$learnerId'
      path: '/sis/learners/$learnerId'
      fullPath: '/modules/sis/learners/$learnerId'
      preLoaderRoute: typeof ModulesSisLearnersLearnerIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/sis/applications_/$applicationId': {
      id: '/modules/sis/applications_/$applicationId'
      path: '/sis/applications/$applicationId'
      fullPath: '/modules/sis/applications/$applicationId'
      preLoaderRoute: typeof ModulesSisApplicationsApplicationIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/requisitions_/$requisitionId': {
      id: '/modules/procurement/requisitions_/$requisitionId'
      path: '/procurement/requisitions/$requisitionId'
      fullPath: '/modules/procurement/requisitions/$requisitionId'
      preLoaderRoute: typeof ModulesProcurementRequisitionsRequisitionIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/procurement/purchase-orders_/$purchaseOrderId': {
      id: '/modules/procurement/purchase-orders_/$purchaseOrderId'
      path: '/procurement/purchase-orders/$purchaseOrderId'
      fullPath: '/modules/procurement/purchase-orders/$purchaseOrderId'
      preLoaderRoute: typeof ModulesProcurementPurchaseOrdersPurchaseOrderIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/assets-inventory/movements_/$movementId': {
      id: '/modules/assets-inventory/movements_/$movementId'
      path: '/assets-inventory/movements/$movementId'
      fullPath: '/modules/assets-inventory/movements/$movementId'
      preLoaderRoute: typeof ModulesAssetsInventoryMovementsMovementIdRouteImport
      parentRoute: typeof ModulesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHostelRoute: typeof AdminHostelRoute
  AdminHrPayrollRoute: typeof AdminHrPayrollRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLicensingRoute: typeof AdminLicensingRoute
  AdminMessagingRoute: typeof AdminMessagingRoute
  AdminProcurementRoute: typeof AdminProcurementRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentProvidersRoute: typeof AdminAgentProvidersRoute
  AdminAgentRoutingRoute: typeof AdminAgentRoutingRoute
  AdminFleetDailyLogRoute: typeof AdminFleetDailyLogRoute
  AdminFleetDriversRoute: typeof AdminFleetDriversRoute
  AdminFleetIndexRoute: typeof AdminFleetIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHostelRoute: AdminHostelRoute,
  AdminHrPayrollRoute: AdminHrPayrollRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLicensingRoute: AdminLicensingRoute,
  AdminMessagingRoute: AdminMessagingRoute,
  AdminProcurementRoute: AdminProcurementRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentProvidersRoute: AdminAgentProvidersRoute,
  AdminAgentRoutingRoute: AdminAgentRoutingRoute,
  AdminFleetDailyLogRoute: AdminFleetDailyLogRoute,
  AdminFleetDriversRoute: AdminFleetDriversRoute,
  AdminFleetIndexRoute: AdminFleetIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ModulesRouteChildren {
  ModulesModuleKeyRoute: typeof ModulesModuleKeyRoute
  ModulesAcademicsAcademicYearsRoute: typeof ModulesAcademicsAcademicYearsRoute
  ModulesAcademicsAssessmentsRoute: typeof ModulesAcademicsAssessmentsRoute
  ModulesAcademicsClassesRoute: typeof ModulesAcademicsClassesRoute
  ModulesAcademicsGradeLevelsRoute: typeof ModulesAcademicsGradeLevelsRoute
  ModulesAcademicsSubjectsRoute: typeof ModulesAcademicsSubjectsRoute
  ModulesAcademicsTeachersRoute: typeof ModulesAcademicsTeachersRoute
  ModulesAcademicsTeachingAssignmentsRoute: typeof ModulesAcademicsTeachingAssignmentsRoute
  ModulesAcademicsTermsRoute: typeof ModulesAcademicsTermsRoute
  ModulesAssetsInventoryItemsRoute: typeof ModulesAssetsInventoryItemsRoute
  ModulesAssetsInventoryMovementsRoute: typeof ModulesAssetsInventoryMovementsRoute
  ModulesAssetsInventoryProcurementReceiptsRoute: typeof ModulesAssetsInventoryProcurementReceiptsRoute
  ModulesAssetsInventoryStockRoute: typeof ModulesAssetsInventoryStockRoute
  ModulesAssetsInventoryStoresRoute: typeof ModulesAssetsInventoryStoresRoute
  ModulesFeesBillingAccountsRoute: typeof ModulesFeesBillingAccountsRoute
  ModulesFeesFeeStructuresRoute: typeof ModulesFeesFeeStructuresRoute
  ModulesFeesImportsRoute: typeof ModulesFeesImportsRoute
  ModulesFeesInvoicesRoute: typeof ModulesFeesInvoicesRoute
  ModulesFinanceAccountingPeriodsRoute: typeof ModulesFinanceAccountingPeriodsRoute
  ModulesFinanceChartOfAccountsRoute: typeof ModulesFinanceChartOfAccountsRoute
  ModulesFinanceCurrenciesRoute: typeof ModulesFinanceCurrenciesRoute
  ModulesFinanceJournalsRoute: typeof ModulesFinanceJournalsRoute
  ModulesFinancePostingRequestsRoute: typeof ModulesFinancePostingRequestsRoute
  ModulesFleetDailyLogRoute: typeof ModulesFleetDailyLogRoute
  ModulesFleetDriversRoute: typeof ModulesFleetDriversRoute
  ModulesFleetVehiclesRoute: typeof ModulesFleetVehiclesRoute
  ModulesHrPayrollAvailabilityRoute: typeof ModulesHrPayrollAvailabilityRoute
  ModulesHrPayrollDepartmentsRoute: typeof ModulesHrPayrollDepartmentsRoute
  ModulesHrPayrollEmployeesRoute: typeof ModulesHrPayrollEmployeesRoute
  ModulesHrPayrollEmploymentRoute: typeof ModulesHrPayrollEmploymentRoute
  ModulesHrPayrollImportsRoute: typeof ModulesHrPayrollImportsRoute
  ModulesHrPayrollPositionsRoute: typeof ModulesHrPayrollPositionsRoute
  ModulesProcurementGoodsReceiptsRoute: typeof ModulesProcurementGoodsReceiptsRoute
  ModulesProcurementPurchaseOrdersRoute: typeof ModulesProcurementPurchaseOrdersRoute
  ModulesProcurementRequisitionsRoute: typeof ModulesProcurementRequisitionsRoute
  ModulesProcurementSuppliersRoute: typeof ModulesProcurementSuppliersRoute
  ModulesSisApplicationsRoute: typeof ModulesSisApplicationsRoute
  ModulesSisEnrolmentsRoute: typeof ModulesSisEnrolmentsRoute
  ModulesSisGuardianRelationshipsRoute: typeof ModulesSisGuardianRelationshipsRoute
  ModulesSisGuardiansRoute: typeof ModulesSisGuardiansRoute
  ModulesSisImportsRoute: typeof ModulesSisImportsRoute
  ModulesSisLearnersRoute: typeof ModulesSisLearnersRoute
  ModulesSisSettingsRoute: typeof ModulesSisSettingsRoute
  ModulesAssetsInventoryMovementsMovementIdRoute: typeof ModulesAssetsInventoryMovementsMovementIdRoute
  ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute: typeof ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute
  ModulesProcurementRequisitionsRequisitionIdRoute: typeof ModulesProcurementRequisitionsRequisitionIdRoute
  ModulesSisApplicationsApplicationIdRoute: typeof ModulesSisApplicationsApplicationIdRoute
  ModulesSisLearnersLearnerIdRoute: typeof ModulesSisLearnersLearnerIdRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesModuleKeyRoute: ModulesModuleKeyRoute,
  ModulesAcademicsAcademicYearsRoute: ModulesAcademicsAcademicYearsRoute,
  ModulesAcademicsAssessmentsRoute: ModulesAcademicsAssessmentsRoute,
  ModulesAcademicsClassesRoute: ModulesAcademicsClassesRoute,
  ModulesAcademicsGradeLevelsRoute: ModulesAcademicsGradeLevelsRoute,
  ModulesAcademicsSubjectsRoute: ModulesAcademicsSubjectsRoute,
  ModulesAcademicsTeachersRoute: ModulesAcademicsTeachersRoute,
  ModulesAcademicsTeachingAssignmentsRoute:
    ModulesAcademicsTeachingAssignmentsRoute,
  ModulesAcademicsTermsRoute: ModulesAcademicsTermsRoute,
  ModulesAssetsInventoryItemsRoute: ModulesAssetsInventoryItemsRoute,
  ModulesAssetsInventoryMovementsRoute: ModulesAssetsInventoryMovementsRoute,
  ModulesAssetsInventoryProcurementReceiptsRoute:
    ModulesAssetsInventoryProcurementReceiptsRoute,
  ModulesAssetsInventoryStockRoute: ModulesAssetsInventoryStockRoute,
  ModulesAssetsInventoryStoresRoute: ModulesAssetsInventoryStoresRoute,
  ModulesFeesBillingAccountsRoute: ModulesFeesBillingAccountsRoute,
  ModulesFeesFeeStructuresRoute: ModulesFeesFeeStructuresRoute,
  ModulesFeesImportsRoute: ModulesFeesImportsRoute,
  ModulesFeesInvoicesRoute: ModulesFeesInvoicesRoute,
  ModulesFinanceAccountingPeriodsRoute: ModulesFinanceAccountingPeriodsRoute,
  ModulesFinanceChartOfAccountsRoute: ModulesFinanceChartOfAccountsRoute,
  ModulesFinanceCurrenciesRoute: ModulesFinanceCurrenciesRoute,
  ModulesFinanceJournalsRoute: ModulesFinanceJournalsRoute,
  ModulesFinancePostingRequestsRoute: ModulesFinancePostingRequestsRoute,
  ModulesFleetDailyLogRoute: ModulesFleetDailyLogRoute,
  ModulesFleetDriversRoute: ModulesFleetDriversRoute,
  ModulesFleetVehiclesRoute: ModulesFleetVehiclesRoute,
  ModulesHrPayrollAvailabilityRoute: ModulesHrPayrollAvailabilityRoute,
  ModulesHrPayrollDepartmentsRoute: ModulesHrPayrollDepartmentsRoute,
  ModulesHrPayrollEmployeesRoute: ModulesHrPayrollEmployeesRoute,
  ModulesHrPayrollEmploymentRoute: ModulesHrPayrollEmploymentRoute,
  ModulesHrPayrollImportsRoute: ModulesHrPayrollImportsRoute,
  ModulesHrPayrollPositionsRoute: ModulesHrPayrollPositionsRoute,
  ModulesProcurementGoodsReceiptsRoute: ModulesProcurementGoodsReceiptsRoute,
  ModulesProcurementPurchaseOrdersRoute: ModulesProcurementPurchaseOrdersRoute,
  ModulesProcurementRequisitionsRoute: ModulesProcurementRequisitionsRoute,
  ModulesProcurementSuppliersRoute: ModulesProcurementSuppliersRoute,
  ModulesSisApplicationsRoute: ModulesSisApplicationsRoute,
  ModulesSisEnrolmentsRoute: ModulesSisEnrolmentsRoute,
  ModulesSisGuardianRelationshipsRoute: ModulesSisGuardianRelationshipsRoute,
  ModulesSisGuardiansRoute: ModulesSisGuardiansRoute,
  ModulesSisImportsRoute: ModulesSisImportsRoute,
  ModulesSisLearnersRoute: ModulesSisLearnersRoute,
  ModulesSisSettingsRoute: ModulesSisSettingsRoute,
  ModulesAssetsInventoryMovementsMovementIdRoute:
    ModulesAssetsInventoryMovementsMovementIdRoute,
  ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute:
    ModulesProcurementPurchaseOrdersPurchaseOrderIdRoute,
  ModulesProcurementRequisitionsRequisitionIdRoute:
    ModulesProcurementRequisitionsRequisitionIdRoute,
  ModulesSisApplicationsApplicationIdRoute:
    ModulesSisApplicationsApplicationIdRoute,
  ModulesSisLearnersLearnerIdRoute: ModulesSisLearnersLearnerIdRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BootRoute: BootRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRouteWithChildren,
  StyleGuideRoute: StyleGuideRoute,
  SetupAdminRoute: SetupAdminRoute,
  SetupSchoolRoute: SetupSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
