version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=campus-pilot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - campus-pilot

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - campus-pilot

  api:
    command: sh -c "wait && /app/app.sh"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      WAIT_HOSTS: redis:6379, db:5432
      WAIT_BEFORE: 30
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_TIMEOUT: 30
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - campus-pilot

  tasks:
    restart: unless-stopped
    build: .
    command: sh rq.sh
    depends_on:
      - api
    networks:
      - campus-pilot

networks:
  campus-pilot:
    driver: bridge