[package]
name = "cp-gradebook"
version = "1.0.0"
edition = "2024"

[dependencies]
cp-common = { path = "../../common" }
cp-audit = { path = "../../platform/audit" }
cp-academics = { path = "../academics" }
cp-sis = { path = "../sis" }

actix-web = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
