CREATE TRIGGER ev_school AFTER INSERT OR UPDATE OR DELETE ON school_profile
FOR EACH ROW EXECUTE FUNCTION log_event();

CREATE TRIGGER ev_users AFTER INSERT OR UPDATE OR DELETE ON users
FOR EACH ROW EXECUTE FUNCTION log_event();
