import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus, Search, UsersRound } from "lucide-react";
import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableControlsBar, TableControlsPagination, TableEmpty, TableError, TableLoading, TableScroll, TableWrap, TBody, TD, TH, THead, TR } from "@/components/ui/data-table";
import { DialogBody, DialogFooter, DialogHeader, DialogShell } from "@/components/ui/dialog";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";
import { responseMessage, transportService } from "./service";
import type { RiderAssignment, RiderStatus, TransportReferences } from "./types";
import { allowed, dateLabel, displayValue, statusTone } from "./ui";

export function TransportRidersWorkspace() {
  const permissions = useAuthStore((state) => state.user?.permissions ?? []); const canConfigure = allowed(permissions, "transport:configure");
  const [records, setRecords] = useState<RiderAssignment[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState<RiderStatus | "all">("active");
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false); const [ending, setEnding] = useState<RiderAssignment | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await transportService.riders({ page, per_page: 25, search: search.trim() || undefined, status: status === "all" ? undefined : status }); if (!response.success || !response.data) throw new Error(responseMessage(response, "Riders could not be loaded")); setRecords(response.data.riders); setTotalPages(response.pagination?.total_pages ?? 1); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Riders could not be loaded"); } finally { setLoading(false); } }, [page, search, status]);
  useEffect(() => { void load(); }, [load]);
  usePageChrome("Riders", canConfigure ? <Button onClick={() => setCreateOpen(true)}><Plus className="size-4" />Assign rider</Button> : null);
  return <div className="space-y-6"><TableControlsBar><Input aria-label="Search riders" className="sm:w-72" leadingIcon={<Search />} onChange={(event) => { setPage(1); setSearch(event.target.value); }} placeholder="Learner name or number" value={search} /><Select aria-label="Rider status" className="sm:w-40" onChange={(event) => { setPage(1); setStatus(event.target.value as RiderStatus | "all"); }} value={status}><option value="all">All statuses</option><option value="active">Active</option><option value="ended">Ended</option><option value="cancelled">Cancelled</option></Select>{!loading && records.length ? <TableControlsPagination onNext={() => setPage((value) => Math.min(totalPages, value + 1))} onPrevious={() => setPage((value) => Math.max(1, value - 1))} page={page} totalPages={totalPages} /> : null}</TableControlsBar><TableWrap>{loading ? <TableLoading columns={7} label="Loading riders…" /> : error ? <TableError description={error} onRetry={() => void load()} /> : records.length === 0 ? <TableEmpty description={canConfigure ? "Assign an active SIS learner to a route." : "No rider assignments are available."} icon={<UsersRound />} title="No riders yet" /> : <TableScroll><Table className="min-w-[1080px]"><THead><tr><TH>Learner</TH><TH>Route</TH><TH>Boarding</TH><TH>Alighting</TH><TH>Effective dates</TH><TH>Status</TH><TH /></tr></THead><TBody>{records.map((record) => <TR key={record.id}><TD><p className="font-medium text-[var(--text-strong)]">{record.learner_name}</p><p className="mt-1 font-tabular text-xs text-[var(--text-muted)]">{record.learner_number}</p></TD><TD><p>{record.route_name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{record.route_code} · {displayValue(record.direction)}</p></TD><TD>{record.boarding_stop_name}</TD><TD>{record.alighting_stop_name}</TD><TD className="whitespace-nowrap text-[var(--text-muted)]">{dateLabel(record.effective_from)} – {dateLabel(record.effective_until)}</TD><TD><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></TD><TD>{canConfigure && record.status === "active" ? <Button onClick={() => setEnding(record)} size="sm" variant="secondary">End</Button> : null}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap><AssignRiderDrawer onClose={() => setCreateOpen(false)} onSaved={() => { setCreateOpen(false); void load(); }} open={createOpen} /><EndRiderDrawer onClose={() => setEnding(null)} onSaved={() => { setEnding(null); void load(); }} record={ending} /></div>;
}

function AssignRiderDrawer({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) {
  const [references, setReferences] = useState<TransportReferences | null>(null); const [error, setError] = useState<string | null>(null); const [learnerSearch, setLearnerSearch] = useState(""); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ learner_id: "", route_id: "", boarding_stop_id: "", alighting_stop_id: "", effective_from: new Date().toISOString().slice(0, 10), effective_until: "" });
  useEffect(() => { if (!open) return; setError(null); setLearnerSearch(""); setForm({ learner_id: "", route_id: "", boarding_stop_id: "", alighting_stop_id: "", effective_from: new Date().toISOString().slice(0, 10), effective_until: "" }); void transportService.references().then((response) => { if (response.success && response.data) setReferences(response.data); else setError(responseMessage(response, "Transport references could not be loaded")); }).catch(() => setError("Transport references could not be loaded")); }, [open]);
  const route = references?.routes.find((item) => item.id === form.route_id); const learners = useMemo(() => { const query = learnerSearch.trim().toLowerCase(); if (!query) return references?.learners ?? []; return (references?.learners ?? []).filter((item) => `${item.display_name} ${item.learner_number}`.toLowerCase().includes(query)); }, [learnerSearch, references]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await transportService.assignRider({ ...form, effective_until: form.effective_until || null }); if (!response.success || !response.data) throw new Error(responseMessage(response, "Rider could not be assigned")); toast.success(`${response.data.learner_name} assigned`); onSaved(); } catch (saveError) { toast.error(saveError instanceof Error ? saveError.message : "Rider could not be assigned"); } finally { setSaving(false); } };
  return <DialogShell onClose={onClose} open={open} panelClassName="max-w-[640px]"><DialogHeader onClose={onClose} title="Assign rider" /><form className="flex min-h-0 flex-1 flex-col overflow-hidden" onSubmit={(event) => void submit(event)}><DialogBody><div className="space-y-5">{error ? <p className="border border-[var(--tone-danger-bd)] bg-[var(--tone-danger-bg)] p-4 text-sm text-[var(--tone-danger)]">{error}</p> : null}<Field label="Find learner"><Input data-autofocus="true" onChange={(event) => setLearnerSearch(event.target.value)} placeholder="Name or learner number" value={learnerSearch} /></Field><Field label="Learner"><Select onChange={(event) => setForm({ ...form, learner_id: event.target.value })} required value={form.learner_id}><option value="">Select learner</option>{learners.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.learner_number}</option>)}</Select></Field><Field label="Route"><Select onChange={(event) => setForm({ ...form, route_id: event.target.value, boarding_stop_id: "", alighting_stop_id: "" })} required value={form.route_id}><option value="">Select route</option>{references?.routes.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code} · {displayValue(item.direction)}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Boarding stop"><Select disabled={!route} onChange={(event) => setForm({ ...form, boarding_stop_id: event.target.value })} required value={form.boarding_stop_id}><option value="">Select stop</option>{route?.stops.map((item) => <option key={item.id} value={item.id}>{item.stop_order}. {item.name}</option>)}</Select></Field><Field label="Alighting stop"><Select disabled={!route} onChange={(event) => setForm({ ...form, alighting_stop_id: event.target.value })} required value={form.alighting_stop_id}><option value="">Select stop</option>{route?.stops.map((item) => <option key={item.id} value={item.id}>{item.stop_order}. {item.name}</option>)}</Select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Effective from"><Input onChange={(event) => setForm({ ...form, effective_from: event.target.value })} required type="date" value={form.effective_from} /></Field><Field label="Effective until"><Input min={form.effective_from} onChange={(event) => setForm({ ...form, effective_until: event.target.value })} type="date" value={form.effective_until} /></Field></div></div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving || !form.learner_id || !form.route_id || !form.boarding_stop_id || !form.alighting_stop_id} type="submit">{saving ? "Assigning…" : "Assign rider"}</Button></DialogFooter></form></DialogShell>;
}

function EndRiderDrawer({ record, onClose, onSaved }: { record: RiderAssignment | null; onClose: () => void; onSaved: () => void }) { const [date, setDate] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => { if (record) { setDate(new Date().toISOString().slice(0, 10)); setReason(""); } }, [record]); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!record) return; setSaving(true); try { const response = await transportService.endRider(record.id, date, reason.trim(), record.version); if (!response.success) throw new Error(responseMessage(response, "Rider assignment could not be ended")); toast.success("Rider assignment ended"); onSaved(); } catch (saveError) { toast.error(saveError instanceof Error ? saveError.message : "Rider assignment could not be ended"); } finally { setSaving(false); } }; return <DialogShell onClose={onClose} open={record !== null} panelClassName="max-w-[560px]"><DialogHeader onClose={onClose} title="End rider assignment" /><form className="flex min-h-0 flex-1 flex-col overflow-hidden" onSubmit={(event) => void submit(event)}><DialogBody><div className="space-y-5"><p className="text-sm text-[var(--text-muted)]">{record?.learner_name} · {record?.route_name}</p><Field label="Last service date"><Input min={record?.effective_from} onChange={(event) => setDate(event.target.value)} required type="date" value={date} /></Field><Field label="Reason"><Textarea data-autofocus="true" maxLength={1000} onChange={(event) => setReason(event.target.value)} required rows={5} value={reason} /></Field></div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving || !date || !reason.trim()} type="submit">{saving ? "Ending…" : "End assignment"}</Button></DialogFooter></form></DialogShell>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }

