import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { BusFront, Plus } from "lucide-react";
import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableControlsBar, TableControlsPagination, TableEmpty, TableError, TableLoading, TableScroll, TableWrap, TBody, TD, TH, THead, TR } from "@/components/ui/data-table";
import { DialogBody, DialogFooter, DialogHeader, DialogShell } from "@/components/ui/dialog";
import { Input, Label, Select } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";
import { responseMessage, transportService } from "./service";
import type { RunStatus, RunSummary, TransportReferences } from "./types";
import { allowed, dateLabel, displayValue, statusTone } from "./ui";

export function TransportRunsWorkspace() {
  const navigate = useNavigate(); const permissions = useAuthStore((state) => state.user?.permissions ?? []); const canOperate = allowed(permissions, "transport:operate");
  const [records, setRecords] = useState<RunSummary[]>([]); const [status, setStatus] = useState<RunStatus | "all">("all"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [createOpen, setCreateOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await transportService.runs({ page, per_page: 25, status: status === "all" ? undefined : status, date_from: dateFrom || undefined, date_to: dateTo || undefined }); if (!response.success || !response.data) throw new Error(responseMessage(response, "Runs could not be loaded")); setRecords(response.data.runs); setTotalPages(response.pagination?.total_pages ?? 1); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Runs could not be loaded"); } finally { setLoading(false); } }, [dateFrom, dateTo, page, status]);
  useEffect(() => { void load(); }, [load]); usePageChrome("Runs", canOperate ? <Button onClick={() => setCreateOpen(true)}><Plus className="size-4" />Create run</Button> : null);
  return <div className="space-y-6"><TableControlsBar><Select aria-label="Run status" className="sm:w-40" onChange={(event) => { setPage(1); setStatus(event.target.value as RunStatus | "all"); }} value={status}><option value="all">All statuses</option>{["draft", "boarding", "departed", "completed", "cancelled"].map((value) => <option key={value} value={value}>{displayValue(value)}</option>)}</Select><Input aria-label="From date" className="sm:w-40" onChange={(event) => { setPage(1); setDateFrom(event.target.value); }} type="date" value={dateFrom} /><Input aria-label="To date" className="sm:w-40" min={dateFrom || undefined} onChange={(event) => { setPage(1); setDateTo(event.target.value); }} type="date" value={dateTo} />{!loading && records.length ? <TableControlsPagination onNext={() => setPage((value) => Math.min(totalPages, value + 1))} onPrevious={() => setPage((value) => Math.max(1, value - 1))} page={page} totalPages={totalPages} /> : null}</TableControlsBar><TableWrap>{loading ? <TableLoading columns={7} label="Loading runs…" /> : error ? <TableError description={error} onRetry={() => void load()} /> : records.length === 0 ? <TableEmpty description={canOperate ? "Create a dated run from an active route." : "No Transport runs are available."} icon={<BusFront />} title="No runs yet" /> : <TableScroll><Table className="min-w-[1080px]"><THead><tr><TH>Run</TH><TH>Route</TH><TH>Vehicle</TH><TH>Driver</TH><TH>Manifest</TH><TH>Status</TH><TH>Date</TH></tr></THead><TBody>{records.map((record) => <TR className="cursor-pointer" key={record.id} onClick={() => void navigate({ to: "/modules/transport/runs/$runId", params: { runId: record.id } })}><TD className="font-tabular font-medium text-[var(--text-strong)]">{record.reference}</TD><TD><p>{record.route_name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{record.route_code} · {displayValue(record.direction)}</p></TD><TD>{record.vehicle_registration}</TD><TD>{record.driver_name}</TD><TD className="font-tabular">{record.boarded_count} boarded · {record.expected_count} expected · {record.exception_count} exceptions</TD><TD><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></TD><TD className="whitespace-nowrap">{dateLabel(record.service_date)}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap><CreateRunDrawer onClose={() => setCreateOpen(false)} onSaved={(record) => { setCreateOpen(false); toast.success(`Run ${record.reference} created`); void navigate({ to: "/modules/transport/runs/$runId", params: { runId: record.id } }); }} open={createOpen} /></div>;
}

function CreateRunDrawer({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (record: RunSummary) => void }) {
  const [references, setReferences] = useState<TransportReferences | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ route_id: "", service_date: new Date().toISOString().slice(0, 10), vehicle_id: "", driver_id: "" });
  useEffect(() => { if (!open) return; setError(null); setForm({ route_id: "", service_date: new Date().toISOString().slice(0, 10), vehicle_id: "", driver_id: "" }); void transportService.references().then((response) => { if (response.success && response.data) setReferences(response.data); else setError(responseMessage(response, "Transport references could not be loaded")); }).catch(() => setError("Transport references could not be loaded")); }, [open]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await transportService.createRun(form); if (!response.success || !response.data) throw new Error(responseMessage(response, "Run could not be created")); onSaved(response.data); } catch (saveError) { toast.error(saveError instanceof Error ? saveError.message : "Run could not be created"); } finally { setSaving(false); } };
  return <DialogShell onClose={onClose} open={open} panelClassName="max-w-[620px]"><DialogHeader onClose={onClose} title="Create run" /><form className="flex min-h-0 flex-1 flex-col overflow-hidden" onSubmit={(event) => void submit(event)}><DialogBody><div className="space-y-5">{error ? <p className="border border-[var(--tone-danger-bd)] bg-[var(--tone-danger-bg)] p-4 text-sm text-[var(--tone-danger)]">{error}</p> : null}<Field label="Service date"><Input data-autofocus="true" onChange={(event) => setForm({ ...form, service_date: event.target.value })} required type="date" value={form.service_date} /></Field><Field label="Route"><Select onChange={(event) => setForm({ ...form, route_id: event.target.value })} required value={form.route_id}><option value="">Select route</option>{references?.routes.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code} · {item.active_rider_count} riders</option>)}</Select></Field><Field label="Vehicle"><Select onChange={(event) => setForm({ ...form, vehicle_id: event.target.value })} required value={form.vehicle_id}><option value="">Select vehicle</option>{references?.vehicles.map((item) => <option key={item.id} value={item.id}>{item.registration_number} · {item.make} {item.model} · {item.capacity} seats</option>)}</Select></Field><Field label="Driver"><Select onChange={(event) => setForm({ ...form, driver_id: event.target.value })} required value={form.driver_id}><option value="">Select driver</option>{references?.drivers.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.license_number}</option>)}</Select></Field></div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving || !form.route_id || !form.vehicle_id || !form.driver_id || !form.service_date} type="submit">{saving ? "Creating…" : "Create run"}</Button></DialogFooter></form></DialogShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
