/** Sensitive pastoral record workspace for boarded learners. */

import { useCallback, useEffect, useState } from "react";
import { HeartHandshake, Plus, Search } from "lucide-react";
import toast from "react-hot-toast";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableControlsBar, TableControlsPagination, TableEmpty, TableError, TableLoading, TableScroll, TableWrap, TBody, TD, TH, THead, TR } from "@/components/ui/data-table";
import { DialogBody, DialogFooter, DialogHeader, DialogShell } from "@/components/ui/dialog";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";

import { hostelService, responseMessage } from "./service";
import type { HostelReferences, PastoralCategory, PastoralRecord, PastoralSeverity } from "./types";
import { dateTime, displayValue, localDateTimeValue, statusTone } from "./ui";

export function HostelPastoralWorkspace() {
  const permissions = useAuthStore((state) => state.user?.permissions ?? []); const canManage = allowed(permissions, "hostel:pastoral");
  const [records, setRecords] = useState<PastoralRecord[]>([]); const [references, setReferences] = useState<HostelReferences | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [category, setCategory] = useState("all"); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [drawerOpen, setDrawerOpen] = useState(false); const [selected, setSelected] = useState<PastoralRecord | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await hostelService.pastoralRecords({ page, per_page: 25, search: search.trim() || undefined, status: status === "all" ? undefined : status, category: category === "all" ? undefined : category }); if (!response.success || !response.data) throw new Error(responseMessage(response, "Pastoral records could not be loaded")); setRecords(response.data.pastoral_records); setTotalPages(response.pagination?.total_pages ?? 1); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Pastoral records could not be loaded"); } finally { setLoading(false); } }, [category, page, search, status]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (canManage) void hostelService.references().then((response) => { if (response.success) setReferences(response.data ?? null); }); }, [canManage]);
  usePageChrome("Pastoral records", canManage ? <Button onClick={() => { setSelected(null); setDrawerOpen(true); }}><Plus className="size-4" />Add record</Button> : null);
  return <div className="space-y-6"><TableControlsBar><Input aria-label="Search pastoral records" className="sm:w-64" leadingIcon={<Search />} onChange={(event) => { setPage(1); setSearch(event.target.value); }} placeholder="Search learner or subject" value={search} /><Select aria-label="Pastoral category" className="sm:w-48" onChange={(event) => { setPage(1); setCategory(event.target.value); }} value={category}><option value="all">All categories</option>{categories.map((value) => <option key={value} value={value}>{displayValue(value)}</option>)}</Select><Select aria-label="Pastoral status" className="sm:w-40" onChange={(event) => { setPage(1); setStatus(event.target.value); }} value={status}><option value="all">All statuses</option><option value="open">Open</option><option value="resolved">Resolved</option></Select>{!loading && records.length ? <TableControlsPagination onNext={() => setPage((value) => Math.min(totalPages, value + 1))} onPrevious={() => setPage((value) => Math.max(1, value - 1))} page={page} totalPages={totalPages} /> : null}</TableControlsBar><TableWrap>{loading ? <TableLoading columns={6} label="Loading pastoral records…" /> : error ? <TableError description={error} onRetry={() => void load()} /> : records.length === 0 ? <TableEmpty description={search || status !== "all" || category !== "all" ? "Change the current filters." : "No pastoral records are in this scope."} icon={<HeartHandshake />} title={search || status !== "all" || category !== "all" ? "No records match" : "No pastoral records yet"} /> : <TableScroll><Table className="min-w-[900px]"><THead><tr><TH>Learner</TH><TH>Subject</TH><TH>Category</TH><TH>Severity</TH><TH>Occurred</TH><TH>Status</TH></tr></THead><TBody>{records.map((record) => <TR className="cursor-pointer" key={record.id} onClick={() => { setSelected(record); setDrawerOpen(true); }}><TD><span className="font-medium text-[var(--text-strong)]">{record.learner_name}</span><p className="mt-1 text-xs text-[var(--text-muted)]">{record.learner_number}</p></TD><TD className="max-w-72 truncate">{record.subject}</TD><TD>{displayValue(record.category)}</TD><TD><Badge tone={statusTone(record.severity)}>{displayValue(record.severity)}</Badge></TD><TD className="whitespace-nowrap text-[var(--text-muted)]">{dateTime(record.occurred_at)}</TD><TD><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></TD></TR>)}</TBody></Table></TableScroll>}</TableWrap><PastoralDrawer canManage={canManage} onClose={() => setDrawerOpen(false)} onSaved={() => { setDrawerOpen(false); void load(); }} open={drawerOpen} record={selected} references={references} /></div>;
}

const categories: PastoralCategory[] = ["wellbeing", "behaviour", "safeguarding", "family_contact", "other"];
const severities: PastoralSeverity[] = ["low", "moderate", "high", "critical"];
function PastoralDrawer({ open, record, references, canManage, onClose, onSaved }: { open: boolean; record: PastoralRecord | null; references: HostelReferences | null; canManage: boolean; onClose: () => void; onSaved: () => void }) {
  const [learnerId, setLearnerId] = useState(""); const [category, setCategory] = useState<PastoralCategory>("wellbeing"); const [severity, setSeverity] = useState<PastoralSeverity>("low"); const [subject, setSubject] = useState(""); const [details, setDetails] = useState(""); const [occurredAt, setOccurredAt] = useState(localDateTimeValue()); const [resolution, setResolution] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setLearnerId(record?.learner_id ?? ""); setCategory(record?.category ?? "wellbeing"); setSeverity(record?.severity ?? "low"); setSubject(record?.subject ?? ""); setDetails(record?.details ?? ""); setOccurredAt(record ? toLocal(record.occurred_at) : localDateTimeValue()); setResolution(""); } }, [open, record]);
  const editable = canManage && (!record || record.status === "open");
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const values = { category, severity, subject: subject.trim(), details: details.trim(), occurred_at: new Date(occurredAt).toISOString() }; const response = record ? await hostelService.updatePastoralRecord(record, values) : await hostelService.createPastoralRecord({ ...values, learner_id: learnerId, allocation_id: null }); if (!response.success) throw new Error(responseMessage(response, "Pastoral record could not be saved")); toast.success(record ? "Pastoral record updated" : "Pastoral record added"); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "Pastoral record could not be saved"); } finally { setSaving(false); } };
  const resolve = async () => { if (!record) return; setSaving(true); try { const response = await hostelService.resolvePastoralRecord(record, resolution.trim()); if (!response.success) throw new Error(responseMessage(response, "Pastoral record could not be resolved")); toast.success("Pastoral record resolved"); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "Pastoral record could not be resolved"); } finally { setSaving(false); } };
  return <DialogShell onClose={onClose} open={open}><form onSubmit={(event) => void save(event)}><DialogHeader onClose={onClose} title={record ? "Pastoral record" : "Add pastoral record"} /><DialogBody><div className="space-y-5">{record ? <div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[var(--text-strong)]">{record.learner_name}</p><p className="mt-1 text-sm text-[var(--text-muted)]">{record.learner_number}{record.residence_name ? ` · ${record.residence_name} · ${record.room_code}` : ""}</p></div><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></div> : <Field label="Learner"><Select data-autofocus="true" onChange={(event) => setLearnerId(event.target.value)} required value={learnerId}><option value="">Select a learner</option>{references?.learners.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.learner_number}</option>)}</Select></Field>}<div className="grid grid-cols-2 gap-4"><Field label="Category"><Select disabled={!editable} onChange={(event) => setCategory(event.target.value as PastoralCategory)} value={category}>{categories.map((value) => <option key={value} value={value}>{displayValue(value)}</option>)}</Select></Field><Field label="Severity"><Select disabled={!editable} onChange={(event) => setSeverity(event.target.value as PastoralSeverity)} value={severity}>{severities.map((value) => <option key={value} value={value}>{displayValue(value)}</option>)}</Select></Field></div><Field label="Occurred at"><Input disabled={!editable} onChange={(event) => setOccurredAt(event.target.value)} required type="datetime-local" value={occurredAt} /></Field><Field label="Subject"><Input disabled={!editable} maxLength={200} onChange={(event) => setSubject(event.target.value)} required value={subject} /></Field><Field label="Details"><Textarea disabled={!editable} maxLength={6000} onChange={(event) => setDetails(event.target.value)} required rows={10} value={details} /></Field>{record?.status === "open" && canManage ? <Field label="Resolution"><Textarea maxLength={4000} onChange={(event) => setResolution(event.target.value)} placeholder="Complete when this record is ready to close" rows={4} value={resolution} /></Field> : record?.resolution ? <ReadValue label="Resolution" value={record.resolution} /> : null}</div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Close</Button>{record?.status === "open" && canManage && resolution.trim() ? <Button disabled={saving} onClick={() => void resolve()} type="button" variant="secondary">{saving ? "Resolving…" : "Resolve record"}</Button> : null}{editable ? <Button disabled={saving || !learnerId || !subject.trim() || !details.trim()} type="submit">{saving ? "Saving…" : "Save record"}</Button> : null}</DialogFooter></form></DialogShell>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function ReadValue({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-subtle)]">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[var(--text-body)]">{value}</p></div>; }
function allowed(permissions: string[], permission: string) { return permissions.includes("*") || permissions.includes(permission); }
function toLocal(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
