/** Room capacity directory and maintenance drawer for Hostel operations. */

import { useCallback, useEffect, useState } from "react";
import { BedDouble, Plus, Search } from "lucide-react";
import toast from "react-hot-toast";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableControlsBar, TableControlsPagination, TableEmpty, TableError, TableLoading, TableScroll, TableWrap, TBody, TD, TH, THead, TR } from "@/components/ui/data-table";
import { DialogBody, DialogFooter, DialogHeader, DialogShell } from "@/components/ui/dialog";
import { Input, Label, Select } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";

import { hostelService, responseMessage } from "./service";
import type { Residence, Room, RoomStatus } from "./types";
import { displayValue, statusTone } from "./ui";

export function HostelRoomsWorkspace() {
  const permissions = useAuthStore((state) => state.user?.permissions ?? []);
  const canCreate = allowed(permissions, "hostel:create"); const canEdit = allowed(permissions, "hostel:edit");
  const [records, setRecords] = useState<Room[]>([]); const [residences, setResidences] = useState<Residence[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [residenceId, setResidenceId] = useState("all"); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [drawerOpen, setDrawerOpen] = useState(false); const [selected, setSelected] = useState<Room | null>(null);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { const response = await hostelService.rooms({ page, per_page: 25, search: search.trim() || undefined, status: status === "all" ? undefined : status, residence_id: residenceId === "all" ? undefined : residenceId }); if (!response.success || !response.data) throw new Error(responseMessage(response, "Rooms could not be loaded")); setRecords(response.data.rooms); setTotalPages(response.pagination?.total_pages ?? 1); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Rooms could not be loaded"); } finally { setLoading(false); }
  }, [page, residenceId, search, status]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void hostelService.residences({ per_page: 100 }).then((response) => { if (response.success && response.data) setResidences(response.data.residences); }); }, []);
  usePageChrome("Rooms & occupancy", canCreate ? <Button onClick={() => { setSelected(null); setDrawerOpen(true); }}><Plus className="size-4" />Add room</Button> : null);
  return <div className="space-y-6"><TableControlsBar><Input aria-label="Search rooms" className="sm:w-64" leadingIcon={<Search />} onChange={(event) => { setPage(1); setSearch(event.target.value); }} placeholder="Search room or residence" value={search} /><Select aria-label="Residence" className="sm:w-52" onChange={(event) => { setPage(1); setResidenceId(event.target.value); }} value={residenceId}><option value="all">All residences</option>{residences.map((record) => <option key={record.id} value={record.id}>{record.name}</option>)}</Select><Select aria-label="Room status" className="sm:w-44" onChange={(event) => { setPage(1); setStatus(event.target.value); }} value={status}><option value="all">All statuses</option><option value="available">Available</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></Select>{!loading && records.length ? <TableControlsPagination onNext={() => setPage((value) => Math.min(totalPages, value + 1))} onPrevious={() => setPage((value) => Math.max(1, value - 1))} page={page} totalPages={totalPages} /> : null}</TableControlsBar><TableWrap>{loading ? <TableLoading columns={6} label="Loading rooms…" /> : error ? <TableError description={error} onRetry={() => void load()} /> : records.length === 0 ? <TableEmpty description={search || status !== "all" || residenceId !== "all" ? "Change the current filters." : "Add rooms to an active residence."} icon={<BedDouble />} title={search || status !== "all" || residenceId !== "all" ? "No rooms match" : "No rooms yet"} /> : <TableScroll><Table className="min-w-[800px]"><THead><tr><TH>Room</TH><TH>Residence</TH><TH>Floor</TH><TH>Status</TH><TH>Occupied</TH><TH>Available</TH></tr></THead><TBody>{records.map((record) => <TR className={canEdit ? "cursor-pointer" : undefined} key={record.id} onClick={() => { if (canEdit) { setSelected(record); setDrawerOpen(true); } }}><TD><span className="font-medium text-[var(--text-strong)]">{record.code}</span><p className="mt-1 text-xs text-[var(--text-muted)]">Capacity {record.capacity}</p></TD><TD>{record.residence_name}</TD><TD className="text-[var(--text-muted)]">{record.floor_label || "—"}</TD><TD><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></TD><TD className="font-tabular">{record.occupied_count} / {record.capacity}</TD><TD className="font-tabular">{record.available_beds}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap><RoomDrawer onClose={() => setDrawerOpen(false)} onSaved={() => { setDrawerOpen(false); void load(); }} open={drawerOpen} record={selected} residences={residences} /></div>;
}

function RoomDrawer({ open, record, residences, onClose, onSaved }: { open: boolean; record: Room | null; residences: Residence[]; onClose: () => void; onSaved: () => void }) {
  const [residenceId, setResidenceId] = useState(""); const [code, setCode] = useState(""); const [floor, setFloor] = useState(""); const [capacity, setCapacity] = useState("1"); const [status, setStatus] = useState<RoomStatus>("available"); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setResidenceId(record?.residence_id ?? ""); setCode(record?.code ?? ""); setFloor(record?.floor_label ?? ""); setCapacity(String(record?.capacity ?? 1)); setStatus(record?.status ?? "available"); } }, [open, record]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const values = { code: code.trim(), floor_label: floor.trim() || null, capacity: Number(capacity) }; const response = record ? await hostelService.updateRoom(record, { ...values, status }) : await hostelService.createRoom({ ...values, residence_id: residenceId }); if (!response.success) throw new Error(responseMessage(response, "Room could not be saved")); toast.success(record ? "Room updated" : "Room added"); onSaved(); } catch (saveError) { toast.error(saveError instanceof Error ? saveError.message : "Room could not be saved"); } finally { setSaving(false); } };
  return <DialogShell onClose={onClose} open={open}><form onSubmit={(event) => void save(event)}><DialogHeader onClose={onClose} title={record ? "Edit room" : "Add room"} /><DialogBody><div className="space-y-5">{record ? <Field label="Residence"><Input disabled value={record.residence_name} /></Field> : <Field label="Residence"><Select data-autofocus="true" onChange={(event) => setResidenceId(event.target.value)} required value={residenceId}><option value="">Select a residence</option>{residences.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}<Field label="Room code"><Input data-autofocus={Boolean(record)} maxLength={40} onChange={(event) => setCode(event.target.value)} required value={code} /></Field><Field label="Floor or area"><Input maxLength={80} onChange={(event) => setFloor(event.target.value)} value={floor} /></Field><Field label="Bed capacity"><Input max={50} min={1} onChange={(event) => setCapacity(event.target.value)} required type="number" value={capacity} /></Field>{record ? <Field label="Status"><Select onChange={(event) => setStatus(event.target.value as RoomStatus)} value={status}><option value="available">Available</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></Select></Field> : null}</div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving || !code.trim() || (!record && !residenceId) || Number(capacity) < 1} type="submit">{saving ? "Saving…" : "Save room"}</Button></DialogFooter></form></DialogShell>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function allowed(permissions: string[], permission: string) { return permissions.includes("*") || permissions.includes(permission); }
