import { useCallback, useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowLeft, HeartPulse, Plus } from "lucide-react";
import toast from "react-hot-toast";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DialogBody, DialogFooter, DialogHeader, DialogShell } from "@/components/ui/dialog";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";

import { healthService, responseMessage, type CareItemPayload } from "./service";
import type { CareItem, CareItemKind, CareSeverity, PatientRecord } from "./types";
import { displayValue, statusTone } from "./ui";

export function HealthPatientRecord({ patientId }: { patientId: string }) {
  const permissions = useAuthStore((state) => state.user?.permissions ?? []);
  const canEdit = permissions.includes("*") || permissions.includes("health:edit");
  const [record, setRecord] = useState<PatientRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false); const [selected, setSelected] = useState<CareItem | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await healthService.patient(patientId); if (!response.success || !response.data) throw new Error(responseMessage(response, "Health patient could not be loaded")); setRecord(response.data); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Health patient could not be loaded"); } finally { setLoading(false); } }, [patientId]);
  useEffect(() => { void load(); }, [load]);
  usePageChrome(record?.person_name ?? "Patient record", canEdit && record ? <Button onClick={() => { setSelected(null); setDrawerOpen(true); }}><Plus className="size-4" />Add care item</Button> : null);
  if (loading) return <div className="h-64 animate-pulse rounded-[var(--radius-xl)] bg-[var(--surface-sunken)]" />;
  if (error || !record) return <div className="rounded-[var(--radius-xl)] border border-[var(--tone-danger-bd)] bg-[var(--tone-danger-bg)] p-6"><p className="font-medium text-[var(--text-strong)]">Patient record could not be loaded</p><p className="mt-1 text-sm text-[var(--text-muted)]">{error}</p><Button className="mt-4" onClick={() => void load()} variant="secondary">Try again</Button></div>;
  return <div className="space-y-6">
    <Link className="inline-flex items-center gap-2 text-sm font-medium text-[var(--text-link)] hover:underline" to="/modules/health/patients"><ArrowLeft className="size-4" />Patients</Link>
    <section className="rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-card)] sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--brand-strong)]">{displayValue(record.person_kind)} · {record.person_number}</p><h1 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-[var(--text-strong)]">{record.person_name}</h1></div><Badge tone={statusTone(record.status)}>{displayValue(record.status)}</Badge></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["Active care items", record.active_care_item_count],["Open visits", record.open_visit_count],["Active medication", record.active_medication_count],["Open follow-ups", record.open_follow_up_count]].map(([label, value]) => <div className="rounded-[var(--radius-lg)] bg-[var(--surface-muted)] p-4" key={String(label)}><p className="text-xs text-[var(--text-muted)]">{label}</p><p className="mt-1 font-tabular text-xl font-semibold text-[var(--text-strong)]">{value}</p></div>)}</div></section>
    <section><h2 className="text-lg font-semibold text-[var(--text-strong)]">Care record</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{record.care_items.length === 0 ? <div className="rounded-[var(--radius-xl)] border border-dashed border-[var(--border)] p-8 text-center"><HeartPulse className="mx-auto size-8 text-[var(--text-subtle)]" /><p className="mt-3 text-sm text-[var(--text-muted)]">No care items recorded.</p></div> : record.care_items.map((item) => <button className="rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface)] p-5 text-left shadow-[var(--shadow-card)] hover:border-[var(--border-strong)]" key={item.id} onClick={() => { if (canEdit) { setSelected(item); setDrawerOpen(true); } }} type="button"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-[var(--text-strong)]">{item.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{displayValue(item.kind)}</p></div><div className="flex gap-2"><Badge tone={statusTone(item.severity)}>{displayValue(item.severity)}</Badge><Badge tone={statusTone(item.status)}>{displayValue(item.status)}</Badge></div></div>{item.details ? <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[var(--text-muted)]">{item.details}</p> : null}</button>)}</div></section>
    {record.person_kind === "learner" ? <section><h2 className="text-lg font-semibold text-[var(--text-strong)]">Current guardian contacts</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{record.guardian_contacts.length === 0 ? <p className="text-sm text-[var(--text-muted)]">No active guardian contact is linked in SIS.</p> : record.guardian_contacts.map((contact) => <div className="rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface)] p-5" key={contact.guardian_id}><div className="flex items-start justify-between gap-3"><p className="font-medium text-[var(--text-strong)]">{contact.display_name}</p>{contact.is_primary ? <Badge tone="info">Primary</Badge> : null}</div><p className="mt-1 text-sm text-[var(--text-muted)]">{displayValue(contact.relationship_type)}</p><p className="mt-4 text-sm text-[var(--text-body)]">{contact.phone || contact.email || "No contact detail recorded"}</p></div>)}</div></section> : null}
    <CareItemDrawer item={selected} onClose={() => setDrawerOpen(false)} onSaved={() => { setDrawerOpen(false); void load(); }} open={drawerOpen} patientId={record.id} />
  </div>;
}

function CareItemDrawer({ open, onClose, onSaved, patientId, item }: { open: boolean; onClose: () => void; onSaved: () => void; patientId: string; item: CareItem | null }) {
  const [kind, setKind] = useState<CareItemKind>("allergy"); const [title, setTitle] = useState(""); const [details, setDetails] = useState(""); const [severity, setSeverity] = useState<CareSeverity>("moderate"); const [reviewedOn, setReviewedOn] = useState(""); const [status, setStatus] = useState<"active" | "resolved">("active"); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open) return; setKind(item?.kind ?? "allergy"); setTitle(item?.title ?? ""); setDetails(item?.details ?? ""); setSeverity(item?.severity ?? "moderate"); setReviewedOn(item?.reviewed_on ?? ""); setStatus(item?.status ?? "active"); }, [item, open]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const payload: CareItemPayload = { kind, title, details: details.trim() || null, severity, reviewed_on: reviewedOn || null }; try { const response = item ? await healthService.updateCareItem(item, { ...payload, status }) : await healthService.createCareItem(patientId, payload); if (!response.success) throw new Error(responseMessage(response, "Care item could not be saved")); toast.success("Care item saved"); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "Care item could not be saved"); } finally { setSaving(false); } };
  return <DialogShell onClose={onClose} open={open}><form onSubmit={(event) => void save(event)}><DialogHeader onClose={onClose} title={item ? "Edit care item" : "Add care item"} /><DialogBody><div className="space-y-5"><Field label="Type"><Select onChange={(event) => setKind(event.target.value as CareItemKind)} value={kind}><option value="allergy">Allergy</option><option value="condition">Condition</option><option value="accommodation">Accommodation</option><option value="action_plan">Action plan</option></Select></Field><Field label="Title"><Input data-autofocus="true" maxLength={160} onChange={(event) => setTitle(event.target.value)} required value={title} /></Field><Field label="Details"><Textarea maxLength={4000} onChange={(event) => setDetails(event.target.value)} rows={6} value={details} /></Field><Field label="Severity"><Select onChange={(event) => setSeverity(event.target.value as CareSeverity)} value={severity}><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option><option value="critical">Critical</option></Select></Field><Field label="Reviewed on"><Input onChange={(event) => setReviewedOn(event.target.value)} type="date" value={reviewedOn} /></Field>{item ? <Field label="Status"><Select onChange={(event) => setStatus(event.target.value as "active" | "resolved")} value={status}><option value="active">Active</option><option value="resolved">Resolved</option></Select></Field> : null}</div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving} type="submit">{saving ? "Saving…" : "Save"}</Button></DialogFooter></form></DialogShell>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
