import { useCallback,useEffect,useState } from "react";
import { ArchiveRestore,Plus,Search } from "lucide-react";
import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";import { Button } from "@/components/ui/button";
import { Table,TableControlsBar,TableEmpty,TableError,TableLoading,TableScroll,TableWrap,TBody,TD,TH,THead,TR } from "@/components/ui/data-table";
import { DialogBody,DialogFooter,DialogHeader,DialogShell } from "@/components/ui/dialog";import { Input,Label,Select,Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";import { useAuthStore } from "@/stores/auth-store";
import { documentRegistryService,responseMessage,type ClassificationPayload } from "./service";import type { Classification,Sensitivity } from "./types";import { label,tone } from "./ui";

export function DocumentRegistryClassificationsWorkspace(){const permissions=useAuthStore((state)=>state.user?.permissions??[]);const canManage=permissions.includes("*")||permissions.includes("document_registry:manage");const[records,setRecords]=useState<Classification[]>([]);const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);const[selected,setSelected]=useState<Classification|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await documentRegistryService.classifications({search:search.trim()||undefined,per_page:100});if(!response.success||!response.data)throw new Error(responseMessage(response,"Classifications could not be loaded"));setRecords(response.data.series)}catch(cause){setError(cause instanceof Error?cause.message:"Classifications could not be loaded")}finally{setLoading(false)}},[search]);useEffect(()=>{void load()},[load]);usePageChrome("Classifications",canManage?<Button onClick={()=>{setSelected(null);setOpen(true)}}><Plus className="size-4"/>Add classification</Button>:null);
 return <div className="space-y-6"><TableControlsBar><Input aria-label="Search classifications" className="sm:w-80" leadingIcon={<Search/>} onChange={(event)=>setSearch(event.target.value)} placeholder="Search code or name" value={search}/></TableControlsBar><TableWrap>{loading?<TableLoading columns={6} label="Loading classifications…"/>:error?<TableError description={error} onRetry={()=>void load()}/>:records.length===0?<TableEmpty description={search?"Change the current search.":"Add the records classifications approved by your campus."} icon={<ArchiveRestore/>} title={search?"No classifications match":"No classifications yet"}/>:<TableScroll><Table className="min-w-[900px]"><THead><tr><TH>Classification</TH><TH>Trigger</TH><TH>Retention</TH><TH>Disposition</TH><TH>Default sensitivity</TH><TH>Files</TH></tr></THead><TBody>{records.map((record)=><TR className={canManage?"cursor-pointer":undefined} key={record.id} onClick={()=>{if(canManage){setSelected(record);setOpen(true)}}}><TD><span className="font-semibold text-[var(--text-strong)]">{record.name}</span><p className="mt-1 text-xs text-[var(--text-muted)]">{record.code} · {label(record.status)}</p></TD><TD>{label(record.retention_trigger)}</TD><TD>{record.retention_period_months===null?"Permanent":`${record.retention_period_months} months`}</TD><TD><Badge tone={tone(record.final_disposition)}>{label(record.final_disposition)}</Badge></TD><TD><Badge tone={tone(record.default_sensitivity)}>{label(record.default_sensitivity)}</Badge></TD><TD className="font-tabular">{record.file_count}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap><ClassificationDrawer onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);void load()}} open={open} record={selected}/></div>}

function ClassificationDrawer({open,record,onClose,onSaved}:{open:boolean;record:Classification|null;onClose:()=>void;onSaved:()=>void}){const[code,setCode]=useState("");const[name,setName]=useState("");const[description,setDescription]=useState("");const[trigger,setTrigger]=useState<"filed"|"closed">("filed");const[months,setMonths]=useState("84");const[disposition,setDisposition]=useState<"review"|"destroy"|"permanent">("review");const[sensitivity,setSensitivity]=useState<Sensitivity>("internal");const[status,setStatus]=useState<"active"|"inactive">("active");const[saving,setSaving]=useState(false);
 useEffect(()=>{if(open){setCode(record?.code??"");setName(record?.name??"");setDescription(record?.description??"");setTrigger(record?.retention_trigger??"filed");setMonths(record?.retention_period_months?.toString()??"");setDisposition(record?.final_disposition??"review");setSensitivity(record?.default_sensitivity??"internal");setStatus(record?.status??"active")}},[open,record]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const payload:ClassificationPayload={code:code.trim(),name:name.trim(),description:description.trim()||null,retention_trigger:trigger,retention_period_months:disposition==="permanent"?null:Number(months),final_disposition:disposition,default_sensitivity:sensitivity};const response=record?await documentRegistryService.updateClassification(record,{...payload,status}):await documentRegistryService.createClassification(payload);if(!response.success)throw new Error(responseMessage(response,"Classification could not be saved"));toast.success(record?"Classification updated":"Classification added");onSaved()}catch(cause){toast.error(cause instanceof Error?cause.message:"Classification could not be saved")}finally{setSaving(false)}};
 return <DialogShell onClose={onClose} open={open}><form onSubmit={(event)=>void save(event)}><DialogHeader onClose={onClose} title={record?"Edit classification":"Add classification"}/><DialogBody><div className="space-y-5"><Field label="Code"><Input data-autofocus="true" maxLength={30} onChange={(event)=>setCode(event.target.value)} required value={code}/></Field><Field label="Name"><Input maxLength={160} onChange={(event)=>setName(event.target.value)} required value={name}/></Field><Field label="Description"><Textarea maxLength={2000} onChange={(event)=>setDescription(event.target.value)} rows={4} value={description}/></Field><Field label="Retention starts"><Select onChange={(event)=>setTrigger(event.target.value as "filed"|"closed")} value={trigger}><option value="filed">When filed</option><option value="closed">When closed</option></Select></Field><Field label="Final disposition"><Select onChange={(event)=>setDisposition(event.target.value as typeof disposition)} value={disposition}><option value="review">Review</option><option value="destroy">Destroy</option><option value="permanent">Permanent</option></Select></Field>{disposition!=="permanent"?<Field label="Retention period (months)"><Input max={1200} min={1} onChange={(event)=>setMonths(event.target.value)} required type="number" value={months}/></Field>:null}<Field label="Default sensitivity"><Select onChange={(event)=>setSensitivity(event.target.value as Sensitivity)} value={sensitivity}><option value="general">General</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></Select></Field>{record?<Field label="Status"><Select onChange={(event)=>setStatus(event.target.value as "active"|"inactive")} value={status}><option value="active">Active</option><option value="inactive">Inactive</option></Select></Field>:null}</div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving||!code.trim()||!name.trim()||(disposition!=="permanent"&&!Number(months))} type="submit">{saving?"Saving…":"Save classification"}</Button></DialogFooter></form></DialogShell>}
function Field({label:fieldLabel,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{fieldLabel}</Label>{children}</div>}
