import { useCallback,useEffect,useState } from "react";
import { ArrowLeft,Download,FileText,Pencil,RefreshCw,ShieldCheck } from "lucide-react";
import { Link } from "@tanstack/react-router";import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";import { Button } from "@/components/ui/button";import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { DialogBody,DialogFooter,DialogHeader,DialogShell } from "@/components/ui/dialog";import { Input,Label,Select,Textarea } from "@/components/ui/input";
import { TableError,TableLoading } from "@/components/ui/data-table";import { usePageChrome } from "@/modules/admin/layouts/page-chrome";import { useAuthStore } from "@/stores/auth-store";
import { documentRegistryService,responseMessage } from "./service";import type { Activity,Classification,RegistryFile,Sensitivity } from "./types";import { bytes,dateTime,dateValue,label,tone } from "./ui";

type Action="edit"|"reclassify"|"close"|null;
export function DocumentRegistryDocumentDetailWorkspace({documentId}:{documentId:string}){const permissions=useAuthStore((state)=>state.user?.permissions??[]);const[record,setRecord]=useState<RegistryFile|null>(null);const[activity,setActivity]=useState<Activity[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[action,setAction]=useState<Action>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[fileResponse,activityResponse]=await Promise.all([documentRegistryService.file(documentId),documentRegistryService.activity(documentId)]);if(!fileResponse.success||!fileResponse.data)throw new Error(responseMessage(fileResponse,"Document could not be loaded"));setRecord(fileResponse.data);setActivity(activityResponse.success&&activityResponse.data?activityResponse.data.activity:[])}catch(cause){setError(cause instanceof Error?cause.message:"Document could not be loaded")}finally{setLoading(false)}},[documentId]);useEffect(()=>{void load()},[load]);usePageChrome(record?.reference??"Document");
 if(loading)return <TableLoading columns={1} label="Loading document…"/>;if(error||!record)return <TableError description={error??"Document not found"} onRetry={()=>void load()}/>;
 const download=async()=>{const popup=window.open("about:blank","_blank");try{const response=await documentRegistryService.download(record.id);if(!response.success||!response.data)throw new Error(responseMessage(response,"Download could not be prepared"));if(popup)popup.location.href=response.data.url;else window.location.assign(response.data.url)}catch(cause){popup?.close();toast.error(cause instanceof Error?cause.message:"Download could not be prepared")}};
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><Link className="inline-flex items-center gap-2 text-sm font-medium text-[var(--text-muted)] hover:text-[var(--text-strong)]" params={{moduleKey:"document-registry"}} to="/modules/$moduleKey"><ArrowLeft className="size-4"/>Documents</Link><div className="flex flex-wrap gap-2"><Button onClick={()=>void download()} variant="secondary"><Download className="size-4"/>Download</Button>{record.status!=="destroyed"&&allowed(permissions,"document_registry:edit")?<Button onClick={()=>setAction("edit")} variant="secondary"><Pencil className="size-4"/>Edit</Button>:null}{record.status!=="destroyed"&&allowed(permissions,"document_registry:classify")?<Button onClick={()=>setAction("reclassify")} variant="secondary"><RefreshCw className="size-4"/>Reclassify</Button>:null}{record.status==="filed"&&allowed(permissions,"document_registry:close")?<Button onClick={()=>setAction("close")}>Close file</Button>:null}</div></div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><CardTitle>{record.title}</CardTitle><div className="flex flex-wrap gap-2 pt-2"><Badge tone={tone(record.status)}>{label(record.status)}</Badge><Badge tone={tone(record.sensitivity)}>{label(record.sensitivity)}</Badge></div></CardHeader><CardContent><dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2"><Datum label="Reference" value={record.reference}/><Datum label="Classification" value={`${record.series_code} · ${record.series_name}`}/><Datum label="Document date" value={dateValue(record.document_date)}/><Datum label="Filed" value={dateValue(record.filed_on)}/><Datum label="Retention" value={record.final_disposition==="permanent"?"Permanent":dateValue(record.retain_until)}/><Datum label="Original file" value={`${record.original_file_name} · ${bytes(record.byte_size)}`}/><Datum label="Security scan" value={dateTime(record.scanned_at)}/><Datum label="SHA-256" value={record.sha256_hex}/></dl>{record.description?<p className="mt-6 whitespace-pre-wrap border-t border-[var(--border)] pt-5 text-sm leading-6 text-[var(--text-muted)]">{record.description}</p>:null}</CardContent></Card>
 <Card><CardHeader><CardTitle>Activity</CardTitle></CardHeader><CardContent>{activity.length===0?<p className="text-sm text-[var(--text-muted)]">No activity recorded.</p>:<ol className="space-y-5">{activity.map((item)=><li className="relative border-l border-[var(--border)] pl-4" key={item.id}><span className="font-medium text-[var(--text-strong)]">{label(item.event_type)}</span><p className="mt-1 text-xs text-[var(--text-muted)]">{dateTime(item.created_at)}</p></li>)}</ol>}</CardContent></Card></div><DocumentActionDrawer action={action} onClose={()=>setAction(null)} onSaved={()=>{setAction(null);void load()}} record={record}/></div>}

function DocumentActionDrawer({action,record,onClose,onSaved}:{action:Action;record:RegistryFile;onClose:()=>void;onSaved:()=>void}){const permissions=useAuthStore((state)=>state.user?.permissions??[]);const[classifications,setClassifications]=useState<Classification[]>([]);const[title,setTitle]=useState(record.title);const[description,setDescription]=useState(record.description??"");const[documentDate,setDocumentDate]=useState(record.document_date??"");const[sensitivity,setSensitivity]=useState<Sensitivity>(record.sensitivity);const[seriesId,setSeriesId]=useState(record.series_id);const[reason,setReason]=useState("");const[saving,setSaving]=useState(false);
 useEffect(()=>{if(!action)return;setTitle(record.title);setDescription(record.description??"");setDocumentDate(record.document_date??"");setSensitivity(record.sensitivity);setSeriesId(record.series_id);setReason("");if(action==="reclassify")void documentRegistryService.classifications({status:"active",per_page:100}).then((response)=>{if(response.success&&response.data)setClassifications(response.data.series)})},[action,record]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!action)return;setSaving(true);try{const response=action==="edit"?await documentRegistryService.updateFile(record,{title:title.trim(),description:description.trim()||null,document_date:documentDate||null,sensitivity}):action==="reclassify"?await documentRegistryService.reclassify(record,{series_id:seriesId,sensitivity,reason:reason.trim()}):await documentRegistryService.close(record,reason.trim());if(!response.success)throw new Error(responseMessage(response,"Document could not be updated"));toast.success(action==="close"?"Document closed":action==="reclassify"?"Document reclassified":"Document updated");onSaved()}catch(cause){toast.error(cause instanceof Error?cause.message:"Document could not be updated")}finally{setSaving(false)}};
 return <DialogShell onClose={onClose} open={Boolean(action)}><form onSubmit={(event)=>void save(event)}><DialogHeader onClose={onClose} title={action==="edit"?"Edit document":action==="reclassify"?"Reclassify document":"Close file"}/><DialogBody><div className="space-y-5">{action==="edit"?<><Field label="Title"><Input data-autofocus="true" onChange={(event)=>setTitle(event.target.value)} required value={title}/></Field><Field label="Description"><Textarea onChange={(event)=>setDescription(event.target.value)} rows={5} value={description}/></Field><Field label="Document date"><Input onChange={(event)=>setDocumentDate(event.target.value)} type="date" value={documentDate}/></Field></>:null}{action==="reclassify"?<Field label="Classification"><Select data-autofocus="true" onChange={(event)=>setSeriesId(event.target.value)} value={seriesId}>{classifications.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</Select></Field>:null}{action!=="close"?<Field label="Sensitivity"><Select onChange={(event)=>setSensitivity(event.target.value as Sensitivity)} value={sensitivity}><option value="general">General</option><option value="internal">Internal</option><option value="confidential">Confidential</option>{allowed(permissions,"document_registry:restricted")?<option value="restricted">Restricted</option>:null}</Select></Field>:null}{action!=="edit"?<Field label="Reason"><Textarea data-autofocus={action==="close"?"true":undefined} onChange={(event)=>setReason(event.target.value)} required rows={5} value={reason}/></Field>:null}</div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving||(action!=="edit"&&!reason.trim())} type="submit">{saving?"Saving…":action==="close"?"Close file":"Save changes"}</Button></DialogFooter></form></DialogShell>}
function Datum({label:fieldLabel,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-subtle)]">{fieldLabel}</dt><dd className="mt-1 break-words text-sm text-[var(--text-strong)]">{value}</dd></div>}
function Field({label:fieldLabel,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{fieldLabel}</Label>{children}</div>}
function allowed(permissions:string[],permission:string){return permissions.includes("*")||permissions.includes(permission)}
