import { useCallback,useEffect,useState } from "react";
import { Link } from "@tanstack/react-router";
import { Archive,Plus,Search } from "lucide-react";
import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table,TableControlsBar,TableControlsPagination,TableEmpty,TableError,TableLoading,TableScroll,TableWrap,TBody,TD,TH,THead,TR } from "@/components/ui/data-table";
import { DialogBody,DialogFooter,DialogHeader,DialogShell } from "@/components/ui/dialog";
import { Input,Label,Select,Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";
import { documentRegistryService,responseMessage } from "./service";
import type { Classification,RegistryFile,Sensitivity } from "./types";
import { bytes,dateValue,label,tone } from "./ui";

export function DocumentRegistryDocumentsWorkspace(){
 const permissions=useAuthStore((state)=>state.user?.permissions??[]);const canCreate=allowed(permissions,"document_registry:create");
 const[records,setRecords]=useState<RegistryFile[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[page,setPage]=useState(1);const[totalPages,setTotalPages]=useState(1);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await documentRegistryService.files({page,per_page:25,search:search.trim()||undefined,status:status==="all"?undefined:status});if(!response.success||!response.data)throw new Error(responseMessage(response,"Documents could not be loaded"));setRecords(response.data.files);setTotalPages(response.pagination?.total_pages??1)}catch(cause){setError(cause instanceof Error?cause.message:"Documents could not be loaded")}finally{setLoading(false)}},[page,search,status]);
 useEffect(()=>{void load()},[load]);usePageChrome("Documents",canCreate?<Button onClick={()=>setOpen(true)}><Plus className="size-4"/>File document</Button>:null);
 return <div className="space-y-6"><TableControlsBar><Input aria-label="Search documents" className="sm:w-80" leadingIcon={<Search/>} onChange={(event)=>{setPage(1);setSearch(event.target.value)}} placeholder="Search reference, title, or classification" value={search}/><Select aria-label="Document status" className="sm:w-44" onChange={(event)=>{setPage(1);setStatus(event.target.value)}} value={status}><option value="all">All statuses</option><option value="filed">Filed</option><option value="closed">Closed</option><option value="destroyed">Destroyed</option></Select>{!loading&&records.length?<TableControlsPagination onNext={()=>setPage((value)=>Math.min(totalPages,value+1))} onPrevious={()=>setPage((value)=>Math.max(1,value-1))} page={page} totalPages={totalPages}/>:null}</TableControlsBar>
 <TableWrap>{loading?<TableLoading columns={6} label="Loading documents…"/>:error?<TableError description={error} onRetry={()=>void load()}/>:records.length===0?<TableEmpty description={search||status!=="all"?"Change the current filters.":"File the first official campus document."} icon={<Archive/>} title={search||status!=="all"?"No documents match":"No documents yet"}/>:<TableScroll><Table className="min-w-[960px]"><THead><tr><TH>Document</TH><TH>Classification</TH><TH>Sensitivity</TH><TH>Status</TH><TH>Filed</TH><TH>Retention</TH></tr></THead><TBody>{records.map((record)=><TR key={record.id}><TD><Link className="font-semibold text-[var(--brand-strong)] hover:underline" params={{documentId:record.id}} to="/modules/document-registry/documents/$documentId">{record.reference}</Link><p className="mt-1 max-w-80 truncate text-sm text-[var(--text-strong)]">{record.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{bytes(record.byte_size)}</p></TD><TD><span className="font-medium">{record.series_name}</span><p className="mt-1 text-xs text-[var(--text-muted)]">{record.series_code}</p></TD><TD><Badge tone={tone(record.sensitivity)}>{label(record.sensitivity)}</Badge></TD><TD><Badge tone={tone(record.status)}>{label(record.status)}</Badge></TD><TD>{dateValue(record.filed_on)}</TD><TD>{record.final_disposition==="permanent"?"Permanent":dateValue(record.retain_until)}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap>
 <UploadDrawer onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);void load()}} open={open}/></div>
}
function UploadDrawer({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:()=>void}){
 const permissions=useAuthStore((state)=>state.user?.permissions??[]);const restricted=allowed(permissions,"document_registry:restricted");const[series,setSeries]=useState<Classification[]>([]);const[seriesId,setSeriesId]=useState("");const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[documentDate,setDocumentDate]=useState("");const[sensitivity,setSensitivity]=useState<Sensitivity>("internal");const[file,setFile]=useState<File|null>(null);const[saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;setSeriesId("");setTitle("");setDescription("");setDocumentDate("");setSensitivity("internal");setFile(null);void documentRegistryService.classifications({status:"active",per_page:100}).then((response)=>{if(response.success&&response.data)setSeries(response.data.series)})},[open]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!file)return;setSaving(true);try{const form=new FormData();form.append("series_id",seriesId);form.append("title",title.trim());form.append("description",description.trim());form.append("document_date",documentDate);form.append("sensitivity",sensitivity);form.append("file",file);const response=await documentRegistryService.upload(form);if(!response.success)throw new Error(responseMessage(response,"Document could not be filed"));toast.success(`Filed ${response.data?.reference??"document"}`);onSaved()}catch(cause){toast.error(cause instanceof Error?cause.message:"Document could not be filed")}finally{setSaving(false)}};
 return <DialogShell onClose={onClose} open={open}><form onSubmit={(event)=>void save(event)}><DialogHeader onClose={onClose} title="File document"/><DialogBody><div className="space-y-5"><Field label="Classification"><Select data-autofocus="true" onChange={(event)=>setSeriesId(event.target.value)} required value={seriesId}><option value="">Choose classification</option>{series.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</Select></Field><Field label="Title"><Input maxLength={240} onChange={(event)=>setTitle(event.target.value)} required value={title}/></Field><Field label="Description"><Textarea maxLength={4000} onChange={(event)=>setDescription(event.target.value)} rows={4} value={description}/></Field><Field label="Document date"><Input onChange={(event)=>setDocumentDate(event.target.value)} type="date" value={documentDate}/></Field><Field label="Sensitivity"><Select onChange={(event)=>setSensitivity(event.target.value as Sensitivity)} value={sensitivity}><option value="general">General</option><option value="internal">Internal</option><option value="confidential">Confidential</option>{restricted?<option value="restricted">Restricted</option>:null}</Select></Field><Field label="Document"><Input accept="application/pdf,image/jpeg,image/png" onChange={(event)=>setFile(event.target.files?.[0]??null)} required type="file"/><p className="text-xs text-[var(--text-muted)]">PDF, JPEG, or PNG. Maximum 15 MB.</p></Field></div></DialogBody><DialogFooter><Button onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving||!file||!seriesId||!title.trim()} type="submit">{saving?"Scanning and filing…":"File document"}</Button></DialogFooter></form></DialogShell>
}
function Field({label:fieldLabel,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{fieldLabel}</Label>{children}</div>}
function allowed(permissions:string[],permission:string){return permissions.includes("*")||permissions.includes(permission)}
