[package]
name = "cp-vehicle-log"
version = "1.0.0"
edition = "2024"

[dependencies]
cp-common = { path = "../../common" }
cp-fleet = { path = "../fleet" }

actix-web = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
validator = { workspace = true }
log = { workspace = true }
