/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BootRouteImport } from './routes/boot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupSchoolRouteImport } from './routes/setup.school'
import { Route as SetupAdminRouteImport } from './routes/setup.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSchoolRoute = SetupSchoolRouteImport.update({
  id: '/setup/school',
  path: '/setup/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup/admin',
  path: '/setup/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boot' | '/login' | '/setup/admin' | '/setup/school'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boot' | '/login' | '/setup/admin' | '/setup/school'
  id: '__root__' | '/' | '/boot' | '/login' | '/setup/admin' | '/setup/school'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BootRoute: typeof BootRoute
  LoginRoute: typeof LoginRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SetupSchoolRoute: typeof SetupSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/school': {
      id: '/setup/school'
      path: '/setup/school'
      fullPath: '/setup/school'
      preLoaderRoute: typeof SetupSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/admin': {
      id: '/setup/admin'
      path: '/setup/admin'
      fullPath: '/setup/admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BootRoute: BootRoute,
  LoginRoute: LoginRoute,
  SetupAdminRoute: SetupAdminRoute,
  SetupSchoolRoute: SetupSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
