/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BootRouteImport } from './routes/boot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SetupSchoolRouteImport } from './routes/setup.school'
import { Route as SetupAdminRouteImport } from './routes/setup.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SetupSchoolRoute = SetupSchoolRouteImport.update({
  id: '/setup/school',
  path: '/setup/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup/admin',
  path: '/setup/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup/admin': typeof SetupAdminRoute
  '/setup/school': typeof SetupSchoolRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boot'
    | '/dashboard'
    | '/login'
    | '/setup/admin'
    | '/setup/school'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boot'
    | '/dashboard'
    | '/login'
    | '/setup/admin'
    | '/setup/school'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boot'
    | '/dashboard'
    | '/login'
    | '/setup/admin'
    | '/setup/school'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BootRoute: typeof BootRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SetupSchoolRoute: typeof SetupSchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/setup/school': {
      id: '/setup/school'
      path: '/setup/school'
      fullPath: '/setup/school'
      preLoaderRoute: typeof SetupSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/admin': {
      id: '/setup/admin'
      path: '/setup/admin'
      fullPath: '/setup/admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BootRoute: BootRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SetupAdminRoute: SetupAdminRoute,
  SetupSchoolRoute: SetupSchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
