import { useCallback,useEffect,useState } from "react";
import { Loader2,Pencil,Settings2 } from "lucide-react";
import toast from "react-hot-toast";
import { Button } from "@/components/ui/button";
import { DialogBody,DialogFooter,DialogHeader } from "@/components/ui/dialog";
import { Label,Select } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { documentRegistryService } from "@/modules/document-registry/service";
import type { Classification } from "@/modules/document-registry/types";
import { learningService,responseMessage } from "./service";
import { GuardedDrawer } from "./guarded-drawer";
import type { LearningSettings } from "./types";

export function LearningSettingsWorkspace(){const [record,setRecord]=useState<LearningSettings|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [open,setOpen]=useState(false);const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await learningService.settings();if(!response.success||!response.data)throw new Error(responseMessage(response,"Learning settings could not be loaded"));setRecord(response.data)}catch(value){setError(value instanceof Error?value.message:"Learning settings could not be loaded")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);usePageChrome("Learning settings",record?<Button onClick={()=>setOpen(true)}><Pencil className="size-4"/>Change</Button>:null);return <div className="space-y-6"><p className="text-sm text-[var(--text-muted)]">Choose the Document Registry classification used when teachers upload resources.</p>{loading?<Panel><Loader2 className="size-5 animate-spin text-[var(--brand-strong)]"/>Loading settings…</Panel>:error?<Panel>{error}<Button className="ml-auto" onClick={()=>void load()} size="sm" variant="secondary">Retry</Button></Panel>:record?<section className="border border-[var(--border)] bg-[var(--surface)] p-6"><Settings2 className="size-5 text-[var(--brand-strong)]"/><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--text-muted)]">Upload classification</p><p className="mt-2 text-lg font-semibold text-[var(--text-strong)]">{record.document_series_name??"Not configured"}</p><p className="mt-2 text-sm text-[var(--text-muted)]">{record.document_series_name?"New uploads are filed under this classification.":"Teachers can link existing governed files, but direct uploads are unavailable."}</p></section>:null}<SettingsDrawer onClose={()=>setOpen(false)} onSaved={value=>{setRecord(value);setOpen(false)}} open={open} record={record}/></div>}

function SettingsDrawer({onClose,onSaved,open,record}:{onClose:()=>void;onSaved:(value:LearningSettings)=>void;open:boolean;record:LearningSettings|null}){const [series,setSeries]=useState<Classification[]>([]);const [seriesId,setSeriesId]=useState(record?.document_series_id??"");const [saving,setSaving]=useState(false);useEffect(()=>{if(!open)return;setSeriesId(record?.document_series_id??"");void documentRegistryService.classifications({status:"active",per_page:100}).then(response=>{if(response.success&&response.data)setSeries(response.data.series)})},[open,record]);if(!record)return null;const dirty=seriesId!==(record.document_series_id??"");const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await learningService.updateSettings(record,seriesId||null);if(!response.success||!response.data)throw new Error(responseMessage(response,"Learning settings could not be updated"));toast.success("Learning settings updated");onSaved(response.data)}catch(value){toast.error(value instanceof Error?value.message:"Learning settings could not be updated")}finally{setSaving(false)}};return <GuardedDrawer dirty={dirty} discardDescription="Your Learning setting has not been saved." onClose={onClose} open={open} pending={saving}>{requestClose=><><DialogHeader onClose={requestClose} title="Learning upload classification"/><form onSubmit={submit}><DialogBody><Label htmlFor="learning-series">Document classification</Label><Select className="mt-1.5" data-autofocus="true" id="learning-series" onChange={event=>setSeriesId(event.target.value)} value={seriesId}><option value="">No direct uploads</option>{series.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</Select><p className="mt-3 text-xs leading-5 text-[var(--text-muted)]">Existing files remain governed by Document Registry when this setting changes.</p></DialogBody><DialogFooter><Button disabled={saving} onClick={requestClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving} type="submit">{saving?<><Loader2 className="size-4 animate-spin"/>Saving…</>:"Save"}</Button></DialogFooter></form></>}</GuardedDrawer>}
function Panel({children}:{children:React.ReactNode}){return <div className="flex min-h-40 items-center gap-3 border border-[var(--border)] bg-[var(--surface)] p-6 text-sm text-[var(--text-muted)]">{children}</div>}
