import { useCallback,useEffect,useState } from "react";
import { Link,useNavigate } from "@tanstack/react-router";
import { BookOpenCheck,Loader2,Plus } from "lucide-react";
import toast from "react-hot-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table,TableControlsBar,TableControlsPagination,TableEmpty,TableError,TableLoading,TableScroll,TableWrap,TBody,TD,TH,THead,TR } from "@/components/ui/data-table";
import { DialogBody,DialogFooter,DialogHeader,DialogShell } from "@/components/ui/dialog";
import { Input,Label,Select,Textarea } from "@/components/ui/input";
import { usePageChrome } from "@/modules/admin/layouts/page-chrome";
import { useAuthStore } from "@/stores/auth-store";
import { learningService,responseMessage } from "./service";
import type { LearningReferenceData,LearningSpaceStatus,LearningSpaceSummary } from "./types";

export function LearningSpacesWorkspace(){
  const navigate=useNavigate();
  const permissions=useAuthStore(state=>state.user?.permissions??[]);
  const canTeach=permissions.includes("*")||permissions.includes("learning:teach");
  const [records,setRecords]=useState<LearningSpaceSummary[]>([]);const [references,setReferences]=useState<LearningReferenceData|null>(null);
  const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [page,setPage]=useState(1);const [totalPages,setTotalPages]=useState(1);
  const [search,setSearch]=useState("");const [status,setStatus]=useState("all");const [createOpen,setCreateOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await learningService.spaces({page,per_page:25,search:search.trim()||undefined,status:status==="all"?undefined:status as LearningSpaceStatus});if(!response.success||!response.data)throw new Error(responseMessage(response,"Learning spaces could not be loaded"));setRecords(response.data.spaces);setTotalPages(response.pagination?.total_pages??1)}catch(value){setError(value instanceof Error?value.message:"Learning spaces could not be loaded")}finally{setLoading(false)}},[page,search,status]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{if(!canTeach)return;void learningService.references().then(response=>{if(response.success&&response.data)setReferences(response.data)})},[canTeach]);
  usePageChrome("Learning spaces",canTeach?<Button onClick={()=>setCreateOpen(true)}><Plus className="size-4"/>New space</Button>:null);
  return <div className="space-y-6"><p className="text-sm text-[var(--text-muted)]">Class learning spaces available to your account.</p>
    <TableControlsBar><Input aria-label="Search learning spaces" className="sm:w-72" onChange={event=>{setPage(1);setSearch(event.target.value)}} placeholder="Search spaces" value={search}/><Select aria-label="Status filter" className="sm:w-44" onChange={event=>{setPage(1);setStatus(event.target.value)}} value={status}><option value="all">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></Select>{!loading&&records.length?<TableControlsPagination onNext={()=>setPage(value=>Math.min(totalPages,value+1))} onPrevious={()=>setPage(value=>Math.max(1,value-1))} page={page} totalPages={totalPages}/>:null}</TableControlsBar>
    <TableWrap>{loading?<TableLoading columns={6} label="Loading learning spaces…"/>:error?<TableError description={error} onRetry={()=>void load()}/>:records.length===0?<TableEmpty description={search||status!=="all"?"Change the current filters.":canTeach?"Create a space from an active teaching assignment.":"No published spaces are available for your classes."} icon={<BookOpenCheck/>} title={search||status!=="all"?"No spaces match":"No learning spaces yet"}/>:<TableScroll><Table className="min-w-[880px]"><THead><tr><TH>Space</TH><TH>Class</TH><TH>Teacher</TH><TH>Status</TH><TH>Units</TH><TH>Updated</TH></tr></THead><TBody>{records.map(record=><TR key={record.id}><TD><Link className="font-semibold text-[var(--text-strong)] hover:text-[var(--brand-strong)] hover:underline" params={{spaceId:record.id}} to="/modules/learning/spaces/$spaceId">{record.title}</Link><p className="mt-1 text-xs text-[var(--text-muted)]">{record.subject_name} · {record.academic_term_name}</p></TD><TD>{record.class_group_name}</TD><TD className="text-[var(--text-muted)]">{record.teacher_name}</TD><TD><StatusBadge status={record.status}/></TD><TD className="font-tabular text-[var(--text-muted)]">{record.published_unit_count} / {record.unit_count} published</TD><TD className="text-[var(--text-muted)]">{dateTime(record.updated_at)}</TD></TR>)}</TBody></Table></TableScroll>}</TableWrap>
    <CreateSpaceDrawer onClose={()=>setCreateOpen(false)} onCreated={id=>{setCreateOpen(false);void navigate({to:"/modules/learning/spaces/$spaceId",params:{spaceId:id}})}} open={createOpen} references={references}/>
  </div>
}

function CreateSpaceDrawer({onClose,onCreated,open,references}:{onClose:()=>void;onCreated:(id:string)=>void;open:boolean;references:LearningReferenceData|null}){
  const [assignmentId,setAssignmentId]=useState("");const [title,setTitle]=useState("");const [summary,setSummary]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{if(open){setAssignmentId(references?.assignments[0]?.id??"");setTitle("");setSummary("")}},[open,references]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!references?.active_term||saving)return;setSaving(true);try{const response=await learningService.createSpace({teaching_assignment_id:assignmentId,academic_term_id:references.active_term.id,title:title.trim(),summary:summary.trim()||null});if(!response.success||!response.data)throw new Error(responseMessage(response,"Learning space could not be created"));toast.success("Learning space created");onCreated(response.data.id)}catch(value){toast.error(value instanceof Error?value.message:"Learning space could not be created")}finally{setSaving(false)}};
  return <DialogShell onClose={onClose} open={open}><DialogHeader onClose={saving?undefined:onClose} title="New learning space"/>{!references?.active_term?<DialogBody><p className="text-sm leading-6 text-[var(--text-muted)]">An active academic term is required before a learning space can be created.</p></DialogBody>:<form onSubmit={submit}><DialogBody className="space-y-5"><div><Label>Academic term</Label><p className="mt-2 text-sm font-medium text-[var(--text-strong)]">{references.active_term.name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{references.active_term.academic_year_name}</p></div><div><Label htmlFor="learning-assignment">Teaching assignment</Label><Select className="mt-1.5" data-autofocus="true" id="learning-assignment" onChange={event=>setAssignmentId(event.target.value)} required value={assignmentId}><option value="">Choose an assignment</option>{references.assignments.map(item=><option key={item.id} value={item.id}>{item.subject_name} · {item.class_group_name} · {item.teacher_name}</option>)}</Select>{references.assignments.length===0?<p className="mt-2 text-xs text-[var(--tone-danger)]">No active teaching assignments are available.</p>:null}</div><div><Label htmlFor="learning-title">Title</Label><Input className="mt-1.5" id="learning-title" maxLength={200} onChange={event=>setTitle(event.target.value)} required value={title}/></div><div><Label htmlFor="learning-summary">Summary</Label><Textarea className="mt-1.5 min-h-32" id="learning-summary" maxLength={4000} onChange={event=>setSummary(event.target.value)} value={summary}/></div></DialogBody><DialogFooter><Button disabled={saving} onClick={onClose} type="button" variant="secondary">Cancel</Button><Button disabled={saving||!assignmentId||!title.trim()} type="submit">{saving?<><Loader2 className="size-4 animate-spin"/>Creating…</>:"Create space"}</Button></DialogFooter></form>}</DialogShell>
}

export function StatusBadge({status}:{status:string}){return <Badge tone={status==="published"?"success":status==="draft"?"warning":"neutral"}>{label(status)}</Badge>}
export function label(value:string){return value.replace(/_/g," ").replace(/^./,letter=>letter.toUpperCase())}
export function dateTime(value:string){return new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
